### ISSUE TITLE
Additional charts?

### ISSUE THREAD

**Issue by esbullington** [esbullington/react-d3#1]
Histogram and scatter plot, I think.  What else?

**Comment by yang-wei** [comment]
Are you interested to implement treemap too ? I'm currently experimenting combining React with d3 treemap ([simple example](https://github.com/yang-wei/react-treemap) and [simple app](https://github.com/yang-wei/gh-top)). I can open a pull request if you're interested =)

**Comment by esbullington** [comment]
@yang-wei sorry for the delay and thanks for your offer to help.  I just put up a CONTRIBUTING file with some detailed guidelines on what new charts would need.   If the guidelines don't scare you away (not my intention, but I realize there are a lot of them), then I'd be very grateful for your treemap chart.

I think the most time-consuming change your current chart would need to make is change from HTML to SVG (using `<rect>` as the main type of element, I'd imagine).  And adding tests (all the charts are currently tested, and I want to keep that up).  An example of its use in the example app would be appreciated, but not necessary.

You can see a d3 treemap using SVG [here](http://bost.ocks.org/mike/treemap/).  Ours definitely doesn't need to be this complex, the way yours works now is just fine except for the HTML instead of SVG.  Changing to SVG will also make it easier to animate/zoom the treemap, which I see you have on your wishlist of things you'd like to add to it.

Thanks again for the offer.

**Comment by yang-wei** [comment]
@esbullington :+1: You're right, they need to be svg-ish to zoom. I will take time to read your guide first and send you a pr =)

**Comment by esbullington** [comment]
@yang-wei I'm closing this issue in favor of opening an additional issue for each possible new chart.

Thanks again for your awesome work on the treemap!
