### ISSUE TITLE
Contributing notes regarding build steps

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#105]
I reinstall node by using nvm, so of course `npm run watch` fails and it took me a while to look at the build steps.  Will be great it all of these are written in CONTRIBUTING.md.

Leaving this issue opening now. Will these notes in `CONTRIBUTING.md` within this week if no one does.

**Comment by esbullington** [comment]
Thanks for letting me know.  Would you mind trying again when you get a chance?  You should be able to just run `npm install` and then `npm run watch` and everything just work now.  Between jmuel's PR and mine, I think we fixed any issues.

You'll get warnings about `react-tools` and `karma-cli` being global installs, but there is no way to avoid those if you want them to be install automatically.

**Comment by esbullington** [comment]
I also [left a note](https://github.com/esbullington/react-d3/wiki/Development) in the wiki, which I refer to now in `CONTRIBUTING.md`.  Do you think this make everything clear?

**Comment by yang-wei** [comment]
Yes it does. And your latest commit should fix them. Will reopen this if there is any problem. Thanks ! @esbullington
