### ISSUE TITLE
Semantic chart className

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#115]
Let's decide standard `className` for each components(or chart) in this library. Would be useful for documentation and tests in the future. The prefix for className I would like to proposed is `rd3`(you guessed it). So every main chart would have at least a `className` on the parent component at their `g` element (child of `svg`).
```
// For example candlestick chart
<svg width={...}>
  <g class='rd3-candlestick' > ... </g>   <--- here
</svg>
```
So other charts' `className` will look like `rd3-barchart`, `rd3-treemap`, `rd3-scatterchart`, `rd3-x-axis` by following class name. (Still thinking to include the word *chart* or not)

We also have child components inside those main chart components. So for example `path` inside `areaChart` will have `rd3-areachart-path` or like [this](https://github.com/esbullington/react-d3/blob/master/src%2Flinechart.jsx#L29)

Same thing for axes.

**Comment by esbullington** [comment]
Yeah, this is definitely needed.  I agree with your namespacing scheme (and yes, I think we go ahead and add `-chart` to the chart `className`).

Do you want to do this @yang-wei?  I know this is a busy time for you.  If not, I'm sure me or someone else can pick it up in the next few days.

Also, let's also add this to the [developer documentation](https://github.com/esbullington/react-d3/wiki/Development) and leave the issue open until it's both implemented and documented:

- [ ] new CSS `className` namespacing implemented in all charts
- [ ] namespace scheme documented in  [developer documentation](https://github.com/esbullington/react-d3/wiki/Development)

**Comment by yang-wei** [comment]
Perfect, if no one is doing this before this coming weekend, then probably I can do it =)

To clear this up, you mean the `className` of barchart will look like `rd3-barchart-chart` while treemap will look like `rd3-treemap-chart`. How about we just keep them shorter like `rd3-barchart`.

**Comment by yang-wei** [comment]
Please have a look at my [draft](https://github.com/esbullington/react-d3/wiki/Development#chart-classname)

**Comment by esbullington** [comment]
Looks great, @yang-wei

**Comment by esbullington** [comment]
@yang-wei Ah, I see now why you had to do `rd3-chart-axis y axis` instead of `rd3-chart y axis` -- it's because React test utilities don't handle combined class names.  We'll stick with what you did, it's the best way given the constraints of the React test tools.  Thanks again, and thanks for the extra tests you put in there!

**Comment by yang-wei** [comment]
Yeah I thought of that too. Closing this now
