### ISSUE TITLE
docs should clarify implementation direction

### ISSUE THREAD

**Issue by srcspider** [esbullington/react-d3#119]
Is this React components that have hacked-in d3
-or-
Is this fully rendered React components with only d3 utility data functions (no d3 rendering)

This make a lot of difference when delaing with server side rendering since having pure react rendering makes everything simpler; no dom emulation nonsense involved.

**Comment by yang-wei** [comment]
@srcspider  Thanks for asking. Couldn't agree more with you that these 2 make a lot of differences and we are also trying our best to render our components purely with `React`.

If you look at our code, most of our components are rendered by `React` but we do have some problems to achieve the same thing for component like `axes`(xAxis and yAxis). However, we do realise this issue. if you look at our [roadmap](https://github.com/esbullington/react-d3#roadmap), we're going to implement pure React component for `axes`. At that time, d3 will be only used for its data functions(no d3 rendering).

We are happy to accept PR regarding to this issue.

**Comment by esbullington** [comment]
Hey @yang-wei I've just about finished the React axes, so no need for PR there.  At that point, project will be purely React rendered.

**Comment by yang-wei** [comment]
Ahh @esbullington that is cool !

**Comment by rrag** [comment]
exciting... I can't wait to try it.

**Comment by srcspider** [comment]
@yang-wei awesome!

One other nit pick. at the moment the package is depending on the entire d3, but if you're rendering in react then you may, depending on what you're rendering, potentially only really need d3 scales (sometimes d3 svg utilities). In fact depending on what you're trying to do you don't even need ALL the scale functions. The source for d3 has them nicely separated into files so technically it should be feasible to include exactly what's required... ie.

```js
var d3 = {
	scale: {
		linear: require('d3/src/scale/linear')
	}
};

SimpleBarChart = React.createClass({
    // ...
```

Sadly as I found out while trying to  achieve that in my own test code, the way d3 source works is a bit annoying in that while at a glance it might look like it's using es6 or something (not that being forced to use a transpiler on it would be that great of a prospect) it's actually using a 3rd-party file concatenation library (https://www.npmjs.com/package/smash) to concat files together that happens to also use the import keyword... ugh!

It's not particularly hard to write scripts to convert the whole import logic to require logic, so that it would actually also work with webpack module dedup-ing (I assume concatting everything would mess with it), but it's more of a "how do you do this in a auto-maintainable way" problem. There seems to be some movement in that direction already https://github.com/mbostock/d3/issues/2220 with the main so hopefully the problem solves itself.

**Comment by esbullington** [comment]
Thanks for your comments.  As you point out, this last issue is out of our control, although we'll happily work with whatever solution Mike comes up with for d3.  If they choose to stick with SMASH, I may create a build with only the parts we need.  Otherwise, if they adopt commonjs, I'll be sure to only require relevant modules.

Your original comment will be addressed with pure React axes in the next release (I opened #126 to track this specifically).   So I'm going ahead and closing this issue.
