### ISSUE TITLE
Inline Styles vs. CSS

### ISSUE THREAD

**Issue by tarrencev** [esbullington/react-d3#12]
How should we be styling chart components? Should we provide a base CSS file which a user can overload or should we use inline styles and allow the user to programmatically dictate styling though props.

I think the inline style approach would make most sense here since we already have a bunch of styling properties that can be specified through the api. Might be weird to split style properties between css and js.

**Comment by jefffriesen** [comment]
I would lean towards passing in styles as props instead of through CSS. There's definitely more and more people doing it, including the React team: https://vimeo.com/116209150

**Comment by jefffriesen** [comment]
While I personally lean towards inline styles, I see the benefits of styling via CSS. [d4](http://visible.io) does a good job of adding classes to each of the elements. You can inspect the example charts and see how he did it.  

I could see a hybrid approach for react-d3. You could attach the necessary classes as CSS hooks to the elements. Then you could pass in a prop that would disable the inline styles so any CSS could be respected. For example:
`<LineChart data={lineData} width={400} height={200} title="Line Chart" enableCSS />`
or 
`<LineChart data={lineData} width={400} height={200} title="Line Chart" disableInlineStyles />`

Maybe this isn't the highest priority but I wanted to suggest a way to do both inline and css styling.

**Comment by esbullington** [comment]
So after lots of discussion with other devs and contributors, I agree that inline styles are the way to go, as long as we make sure to expose lots of class hooks for future designers to use for CSS styling (just as you point out is done in d4 -- a very cool project btw).

So I'm closing this issue: inline styles it is.  Thanks for bringing it up for explicit discussion.
