### ISSUE TITLE
Treemap or TreemapChart

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#122]
Was thinking about this a while ago. Thought it would be nice to have every chart components' name look like `...Chart` but when I look at the [wikipedia page of charts](http://en.wikipedia.org/wiki/Chart) , tree map is just called tree map. Instead of tree map chart.

@esbullington What do you think ?

**Comment by esbullington** [comment]
Hey @yang-wei I think it's fine as it is for now.  If it appears to be confusing people then we can revisit the issue.
