### ISSUE TITLE
Pure React axes

### ISSUE THREAD

**Issue by esbullington** [esbullington/react-d3#126]
I've got a working branch with pure React axes that I'll be pushing out soon (still having issues with text rendering not looking like the original d3 axes) but in the meantime I'll use this issue to track it.

**Comment by esbullington** [comment]
If anyone would like to take a look at `esbullington-features/pure-react-axes` and take a guess as to why the text in my React axes is not rendering as smoothly as d3's, I'd be much obliged.

**Comment by frederickfogerty** [comment]
Looks fine, if not identical, to me. Checked on both retina and non-retina screens.

**Comment by frederickfogerty** [comment]
Before:
![screenshot 2015-02-20 12 18 03](https://cloud.githubusercontent.com/assets/615334/6278289/b3a91f76-b8fa-11e4-9ebb-4667daab653d.png)
After:
![screenshot 2015-02-20 12 18 26](https://cloud.githubusercontent.com/assets/615334/6278290/b3cc969a-b8fa-11e4-9274-e1dc9bb8d5b3.png)

**Comment by esbullington** [comment]
Thanks for checking that, much appreciated.  I think I got it matched now by decreasing the stroke width a little more.

**Comment by esbullington** [comment]
Done and merged.  Thanks for checking that, @frederickfogerty
