### ISSUE TITLE
Setting SVG viewBox attribute

### ISSUE THREAD

**Issue by jxnblk** [esbullington/react-d3#128]
Maybe I've missed how to do this, but it seems like it would be useful to have the `viewBox` attribute for SVG set by default or through props for use in fluid layouts without the need to listen to window resize events. I know this would also scale text used in titles and labels, but it would still be helpful in certain situations.

**Comment by esbullington** [comment]
This is an excellent point.  We can set the `viewBox` and let the chart user set the parent component's width and height.  That should work well.

Only possible issue is IE9+.  Seems like I remember some cross-browser issues with `viewBox` that have made me just use resize events in the past.

Either way, I'll definitely expose it to the user.

**Comment by jxnblk** [comment]
Great, thanks! :boom: 

At least for my use-case with internal tools, we only support Chrome and Firefox, so I could definitely use this.

**Comment by jmuel** [comment]
Has there been progress on this? If there hasn't is there anything I can do to help?

**Comment by esbullington** [comment]
Yes, it's been merged to `master` with the 0.3 branch, but not yet published to NPM.  I've been quite sick for several weeks with a bad case of the flu, and I'm just now catching up on stuff.

Anyway, if you're using the Github repo, you can set the SVG `viewBox` string on any of the Cartesian-coordinate charts (ie, scatter, line, and candle charts at this point).  Not well tested, so let me know if you have any problems.  That would actually be a big help.

I hope to have 0.3 published to NPM in the next few days after I test out some of the new features.

**Comment by jmuel** [comment]
Thanks. I'll probably wait for the npm release but if I get bored I'll play around with the current branch.

**Comment by yang-wei** [comment]
@jmuel We forget to refer to this issue when we solved this. But I suppose https://github.com/esbullington/react-d3/blob/master/src%2Fcommon%2Fcharts%2FBasicChart.jsx#L11

**Comment by jmuel** [comment]
Thanks, that looks like it should do it.
