### ISSUE TITLE
Legends / Labels for Line Charts?

### ISSUE THREAD

**Issue by songgao** [esbullington/react-d3#13]
Hello, thanks for the nice work!

What do you think of adding legends/labels to line charts? When you have more than one data series, it can be hard to tell which is which.

To implement the legends, it seems that a new `prop` need to be added into `LineChart`. The reason that keys of `data` would not work is that, users might want to have same legend/label for different data series. A possible way is to have a `prop.legends` map, with keys corresponding to the ones in `data`.

What do you think?

**Comment by esbullington** [comment]
Hi @songgao thanks for your comment.  Yes, legends with keys corresponding to the series name in the `data` prop would be great, thanks!

Please just make sure to avoid React's `state` when you generate the svg markup.  I'm in the process of creating React-generated chart axes (right now they're generated by d3).  This change will allow me to drop all uses of `state` in the existing charts, and only use `props` to propagate any data changes (and thus vastly simplify the React lifecycle for these charts, as well as testing the code).

Specifically, this means you'd need to use only React to produce the legend svg, and avoid any use of d3 for svg generation.

If you could add a test to accompany your PR, it would be much appreciated (let me know if you have any questions about testing framework).

Thanks again, and look forward to your pull request.

**Comment by songgao** [comment]
Thanks for the detailed response @esbullington . React generated axes sounds awesome! Looking forward to that update :D I'll take a look at the testing framework and include a test.

**Comment by esbullington** [comment]
Hey @songgao are you working on legends?  Otherwise, I'm going to start on them soon.  Thanks again!

**Comment by songgao** [comment]
Hi @esbullington ! Thanks for getting back to this. I haven't got time to really work on the PR. Sorry about that. Please feel free to start on it and I'll try to do some code review.

Yeah pure React axes seems fairly complicated to me as well. But it seems to be something necessary for `react-d3` to gain more popularity. Hopefully I can contribute to this some time in the future :D

**Comment by esbullington** [comment]
Hi @songgao thanks for letting me know.  But please feel free to submit a PR when you have more time, if you would like to.

I'll keep this open until one of us finishes the legends.

**Comment by esbullington** [comment]
This is merged, and will be in our next release. Thanks again for filing the issue, @songgao As you are familiar with dataviz, I'd love to have your continued input.  I'm still thinking about your other issue #14 , which brought up using seriesname mapped to dataseries array vs multidimensional array for data.  The underlying `color` issue is definitely a bug, but not sure how I want to go about fixing it.

**Comment by songgao** [comment]
Thanks @esbullington for getting it merged! The legends looks great!
