### ISSUE TITLE
BarChart axis labels do not work

### ISSUE THREAD

**Issue by grahamb** [esbullington/react-d3#164]
[Sample JSFiddle](http://jsfiddle.net/grahamb/9cmL2yLh/3/)

Problem: BarChart components don't display axis labels.

Steps to reproduce:
Create a `<BarChart>` component with `xAxisLabel` and `yAxisLabel` props.
```
var barData = [{label: 'A', value: 5}, {label: 'B', value: 6}, {label: 'C', value: 2}, {label: 'D', value: 11}, {label: 'E', value: 2}, {label: 'F', value: 7}];

var Hello = React.createClass({
    render: function() {
        return (
                <BarChart
                  data={barData}
                  width={500}
                  height={300}
                  title='Bar Chart'
                  yAxisLabel="y axis"
                  xAxisLabel="x axis"
                />
        );
    }
});
React.render(<Hello />, document.body);
```
Expected result: a `<BarChart>` should be rendered **with both X and Y axis labels visible**.

Actual result: a `<BarChart>` is rendered **without any axis labels visible**.
![screen shot 2015-03-22 at 20 07 26](https://cloud.githubusercontent.com/assets/146111/6773483/1ac0b44e-d0cf-11e4-9b0e-fe444f4db42e.png)

--------

It looks like the `[x|y]AxisLabel` and `[x|y]AxisLabelOffset` props aren't being passed to the `<XAxis>` and `<YAxis>` components inside [`BarChart`](https://github.com/esbullington/react-d3/blob/d69a059e4e8d7d8ba1c58db3ebebe420de5e0e31/src/barchart/BarChart.jsx#L71), as they are inside [`LineChart`](https://github.com/esbullington/react-d3/blob/d69a059e4e8d7d8ba1c58db3ebebe420de5e0e31/src/linechart/LineChart.jsx#L116).

I tried adding in those props to `BarChart`…

![screen shot 2015-03-22 at 20 15 44](https://cloud.githubusercontent.com/assets/146111/6773648/4bf03f1a-d0d1-11e4-9455-28f69593d665.png)

… which causes the labels to render, but the offsets are messed up.

![screen shot 2015-03-22 at 20 24 09](https://cloud.githubusercontent.com/assets/146111/6773659/7b56ddea-d0d1-11e4-9834-c95eb15eb719.png)

---------

Also note in the [Sample JSFiddle](http://jsfiddle.net/grahamb/9cmL2yLh/3/) that the rendering of two charts is a bit messed up. In the example, the top `LineChart` is rendering over the `<hr>` in between it and the bottom `BarChart`.

**Comment by yang-wei** [comment]
Thanks for the well described issue @grahamb. Your description makes debugging faster. Turn out we just forgot to include mixin in `BarChart.jsx` to render x,y axes label.
