### ISSUE TITLE
Support es6 by babeljs

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#174]

**Comment by esbullington** [comment]
Hi @yang-wei well-done with all those PRs!

babeljs is a very cool project, and I'm following it closely.  What particular es6 features are you interested in using that we don't have now?

I do really like how babeljs is very compatible with React as well as with Flow type annotations.  I've been wanting to eventually add Flow compatibility to the project for a while (which actually won't require us to type annotate all the variables, probably just a few thanks to Flow's type inference).

**Comment by yang-wei** [comment]
One of the es6 features I am really interested in is `[destructing](https://github.com/lukehoban/es6features#destructuring)`. 

```js
// currently we do
var common = require('../common');
var Chart = common.Chart;
var XAxis = common.XAxis;
var YAxis = common.YAxis;

// cleaner way
var common = require('../common');
var { Chart, XAxis, YAxis } = common;

// or even better
import { Chart, XAxis, YAxis } from '../common';
```

I can't think of other features which are useful yet but since babeljs is supporting `jsx`, I think it's good to make a switch.

**Comment by esbullington** [comment]
JSTransform supports destructuring, so we can use it now. And we can also use es6 in `jsx`, so any es6 feature you use in your JS, you should also be able to use in the `jsx`.

My main concern with BabelJS is the size of the polyfills.  I've already added significant size with immstruct, which I've not yet had time to replace with something smaller.  So I'm hesitant to pile on additional runtime dependencies, unless I know that they're very insignificant.

Do you know how much larger our build would be using BabelJS?

**Comment by yang-wei** [comment]
> JSTransform supports destructuring
Never know this. Thanks !

One of the thing I came out with is this [section](https://babeljs.io/docs/faq/#no-runtime-dependency) in BabelJS FAQ. Does this solve what you're concerning about. But since most of the es6 features are available, I am closing this.

**Comment by yang-wei** [comment]
@esbullington 
> I've already added significant size with immstruct
Can I know how do you measure this?

**Comment by esbullington** [comment]
Hey @yang-wei how's school going?

It's strange that BabelJS has that section, because I also was reading [this section](https://babeljs.io/docs/usage/caveats/) about polyfills.  It's possible that it's changing so fast that they no longer require those polyfills, and that the documentation is old.  Or perhaps vice versa.

Please feel free to re-open if there's an ES6 feature you'd like to use that JSTransform doesn't cover.  It may be that BabelJS isn't going to add anything polyfills, or maybe just a tiny one.

**Comment by esbullington** [comment]
Re: how to measure size, I just did:

`NODE_ENV=production browserify -t [ reactify --es6 ] --standalone rd3 ./build/cjs/index.js | uglifyjs -c > testpackage.min.js`

And compared the size of the output with and without the package I'm testing.

**Comment by yang-wei** [comment]
I will deep into babeljs doc again when I have time for this.

 > Hey @yang-wei how's school going?

Everything is good for me. Can go back to "normal life" after this weekend. Hope that you're doing well with your career too. Are you?

**Comment by yang-wei** [comment]
The maintainer of babel answered. using `gulp-babel` will not included polyfill by default.

https://github.com/babel/gulp-babel/issues/25#event-278206934

**Comment by esbullington** [comment]
Hey, @yang-wei, are you able to use all the ES6 features you are wanting now?

**Comment by yang-wei** [comment]
oh yes, so I am closing this now.

**Comment by yang-wei** [comment]
The react comminity is moving into es6 (class, es6 module loader, const), plus reactify is no actively maintained, so I think we should move on too. 


Tested out babelify today and it seems it does not add on unnecessary dependencies.

```
NODE_ENV=production browserify -t [ reactify --es6 ] --standalone rd3 ./build/cjs/index.js | uglifyjs -c > testpackage.min.js

// babelify
NODE_ENV=production browserify -t babelify --standalone rd3 ./build/cjs/index.js | uglifyjs -c > testpackage.min.js
```

And the result
![image](https://cloud.githubusercontent.com/assets/5494874/8894149/046a3ece-33e7-11e5-9a22-6243075fb0b6.png)
