### ISSUE TITLE
I can't get it to draw the example charts.

### ISSUE THREAD

**Issue by aj0strow** [esbullington/react-d3#176]
Hello, can't for the life of me get `react-d3` to draw an example chart. I tried using the most recent release in js fiddle:

```html
<script src="http://facebook.github.io/react/js/jsfiddle-integration.js"></script>
<script src="https://raw.githubusercontent.com/esbullington/react-d3/master/dist/public/js/react-d3.min.js"></script>
```

Which errors:

```
Uncaught ReferenceError: rd3 is not defined
```

When I try to use `react-d3` in my own project, i get errors too:

```
Uncaught TypeError: Can't add property context, object is not extensible
```

When i comment out the react d3 chart, the errors go away (but the potential for interpreting data also goes away ...) I must be doing something stupid, but cannot figure it out. Is the current release just broken, and if so, is there a working release? 

Would really love to take it for a spin. Thank you.

**Comment by esbullington** [comment]
Pretty sure your first error is due to the fact that Github doesn't serve files with the content-type header that you need to use them in your project.

Is your second error using Browserify or Webpack, or are you using the minified react-d3 file?  This package is really meant to be used as a CommonJS package -- the compiled, minified version is mostly for the JSFiddle integration.

Can you please show me exactly what you're doing in a [JSFiddle](http://jsfiddle.net/esbullington/jp9dkh1g/)?

**Comment by aj0strow** [comment]
It seems to work in the fiddle, but I still can't get a hello word type thing to work. I keep getting:

```
Uncaught TypeError: Can't add property context, object is not extensible
``` 

The code is just nested views:

```js
// subscriptions.js

var React = require('react')
var BarChart = require('react-d3').BarChart

var barData = [
  {label: 'A', value: 5},
  {label: 'B', value: 6},
  {label: 'F', value: 7}
];

var Subscriptions = React.createClass({
  render: function () {
    return (<div>
      <BarChart data={ barData } width={500} height={200} fill={'#3182bd'} title='Bar Chart' />
    </div>)
  },
})

module.exports = Subscriptions

// application.js

var React = require('react')
var Subscriptions = require('./widget/subscriptions')

var Application = React.createClass({
  render: function () {
    return (
      <div>
        <div className="container-fluid">
          <Subscriptions />
        </div>
      </div>
    )
  }
})

React.render(<Application />, document.getElementById('application'))
```

If i change subscriptions to the following render:

```js
    return (<div>
      <p>hello</p>
    </div>)
```

The error goes away. So it's definitely the chart causing it. I just don't understand how or why, considering it works so well in all the demos and on jsfiddle.

**Comment by aj0strow** [comment]
```
    "react": "^0.13.1",
    "react-d3": "^0.3.0",
```

**Comment by esbullington** [comment]
If you're using browserify or webpack, you may want to give it another try.  I just pushed out a patch that I hope will solve your issue.

**Comment by yang-wei** [comment]
@aj0strow Is your problem solved?

**Comment by esbullington** [comment]
Closed due to inactivity, please feel free to re-open if you're still having issues.
