### ISSUE TITLE
envify required for browserify?

### ISSUE THREAD

**Issue by unbracketed** [esbullington/react-d3#18]
I installed the lib via `npm install --save react-d3` and have v0.0.13. browserify/watchify started complaining about `Cannot find module envify`. 

I resolved this locally by running `npm install` from the `node_modules/react-d3` directory, but would like to understand how I can get this working in an automated build if possible.

Thanks for the great work.

**Comment by esbullington** [comment]
Hi, thanks for opening an issue.  Looks like your `npm install` is not installing the dev dependencies, many of which you need since you're building it using browserify.

Are you running this with `NODE_ENV` set on `development` or `production`?

**Comment by unbracketed** [comment]
I don't have `NODE_ENV` set to anything explicitly.

**Comment by esbullington** [comment]
I have no idea why that would happen.  Unless `NODE_ENV` is set to `production`, running `npm install` should pull in *all* dependencies, dev and non-dev, and `envify` is listed as a dev dependency.  To be honest, we're not even using `envify` yet, but this I'm pretty sure this is a symptom of the dev dependencies not getting installed, and not of `envify` in particular not getting installed (it's just first on the list).  So removing envify from the requirements wouldn't even help -- we *have* to have reactify, which is also listed in dev depencies.

Is this on Linux?

**Comment by esbullington** [comment]
Hi @unbracketed I just released a version 0.1.2 with some `package.json` so if you would like to try upgrading and see if it solves your issue, that would be great.  Thanks again for opening the issue.

**Comment by unbracketed** [comment]
Thanks, I'll test this ASAP

**Comment by unbracketed** [comment]
I'm not seeing the problem I described any longer, thanks. 

Now, during my Gulp build step, I'm getting compile errors (presumably from browserify) like 
```
Cannot find module './barchart' from <path/to/node_modules>
Cannot find module './linechart' from <path/to/node_modules>
...etc...
```

but the graphs show up on the page correctly, so not sure what those are about yet.

**Comment by esbullington** [comment]
Hmm, did you uninstall react-d3 first and then run `npm cache clean`?  If not, you may want to try that to see if it gets rid of these compile errors.  If not, please feel free to open an issue and we'll try to figure it out.

Also, I noticed you work for a very [interesting company](https://lincolnloop.com/blog/how-we-work-talk/), and one that hires remote workers .  Are you all hiring?

**Comment by unbracketed** [comment]
Thank you for the cache tip, I forgot about that.

The problem was due to a recent change renaming .js --> .jsx. I didn't have Browserify configured to look for the .jsx module extension so it wasn't picking those files up. I assume many people already have this configured; all the files in my project to date have only been using .js.

Send us an email, we'd be happy to get in touch when there's an opportunity.
