### ISSUE TITLE
specifying min/max range for the Y axis in a linechart?

### ISSUE THREAD

**Issue by nurpax** [esbullington/react-d3#185]
Is there a way to specify a minimum value for the Y value in a LineChart?

Currently it automatically computes min/max Y values and scales the plot to fit into that range.  E.g., if my values are between 100 and 200, the bottom of the chart starts at 100.  But for many purposes, I'd actually like it to start at zero.

Here's a fiddle that demonstrates what I mean: http://jsfiddle.net/ux1cveed/

**Comment by nurpax** [comment]
I think `domain` is the way this is specified in d3.  But I'd be fine with just setting a floating point value like 

<LineChart yMin=0 .. />

Perhaps this already exists, I just couldn't find the API ref.

**Comment by nurpax** [comment]
@esbullington Please see the PR for what I mean.  There may be better ways of accomplishing the same, this is more of an illustration.

It'd be nice to be able to specify one or the other or both of min/max.  E.g., if I give yMin:0, then it'd use zero as the chart minimum but let d3 compute the max Y value automatically.

I think getting this functionality in one way or the other is an absolute must.  Most of the time, people want their line chart y-min to be at zero.  Unless, of course, you're a marketroid or a statistician wanting to distort reality. :)

**Comment by yang-wei** [comment]
Thanks @nurpax. This is a great feature that we are missing. What do you think about xAxis ?

Also same api should be added to other chart as well.

**Comment by esbullington** [comment]
Hi @nurpax thanks for your comments.  As of now, users can pass in custom chart domain by passing in a custom d3 scale using the `xScale` or `yScale` properties on each chart that accommodates Cartesian coordinates.  But I'm not opposed to offering a more direct way to do this, like you're suggesting.

So if you're willing to submit a PR generalizing the change you made to the line chart in your repo to all the charts that use a Cartesian grid, that would be great.

By the way @yang-wei , I do think `yDomain` is OK for the same reason that the name `yScale` is OK -- like the scale, the domain pertains to the entire chart.  Does that sound reasonable?

**Comment by parshap** [comment]
> As of now, users can pass in custom chart domain by passing in a custom d3 scale using the xScale or yScale properties on each chart that accommodates Cartesian coordinates.

@esbullington: I'm probably just missing it, but I don't see this. Is `props.xScale` and `props.yScale` support for Cartesian charts in master?

**Comment by esbullington** [comment]
Hmm, you're right.  That ability seems to have been lost as I made the React-based axes and restructured the code base.  Now that I'm thinking about it, it may not have even been in all the charts to begin with.

Well, passing in custom scales is probably a must, and this makes @nurpax 's suggestion even more important.  Unless someone else wants to work on it before then, I'll see what I can do this weekend, or possibly before then.

**Comment by parshap** [comment]
@esbullington I needed to be able to set a pass a scale prop to the area chart, so I've added that functionality here: https://github.com/esbullington/react-d3/compare/master...aboutLife:scale-props. I'm not sure I'll be able to get to the other charts, but hopefully this is a start.

**Comment by parshap** [comment]
I added another commit to be able to pass in just the domain instead of computing the whole d3 scale object myself. This is basically the same as @nurpax's commit above, except on top of my previous refactoring.

It turns out that I wasn't able to generate the `yScale` completely myself because I still need the range to be computed using the internal `innerHeight`. My use case is that I want some extra padding at the top of the axis. This is basically the same as d3's `scale.nice()`, but using my own custom values.

It'd be nice if there was a "hook" mutate scale objects instead of having to have different props for every thing you might want to do to the scale.

**Comment by nurpax** [comment]
How does it look like with @parshap 's change, would that be enough to implement yScale and thus to yMin/yMax functionality I suggested?  I'm happy to use yScale but as pointed out above, it seems like the master version or the latest release doesn't have this prop.

I'm happy to drop my PR if there's a more generic version that implements the same thing.  I wasn't planning on extending my change for other chart types.

**Comment by yang-wei** [comment]
Close due to inactive. Please open a new issue to make further discussion.

**Comment by tylerlindell** [comment]
does this work now? If so, how?
