### ISSUE TITLE
bar chart with negative numbers

### ISSUE THREAD

**Issue by kriswallsmith** [esbullington/react-d3#188]
I need to be able to render a chart with negative numbers, like so…

![screen shot 2015-04-18 at 8 35 49 am](https://cloud.githubusercontent.com/assets/33886/7216069/275d7b9c-e5a6-11e4-9d77-34f5af68fc0c.png)

Unfortunately a data array with a negative value throws an error…

>Error: Invalid negative value for <rect> attribute height="-128.46135247235017"

**Comment by jsanchez034** [comment]
Hey @kriswallsmith, @esbullington, have a fix for this issue and I'm about create the pull request for the fix

**Comment by jsanchez034** [comment]
Hey @esbullington here is my pull request with fix, #189.  Let me know what you think.

**Comment by yang-wei** [comment]
@kriswallsmith Give it a try on latest master =)

**Comment by kriswallsmith** [comment]
That works. Thank you!
