### ISSUE TITLE
Add subchart data points (circles)

### ISSUE THREAD

**Issue by danpatnate** [esbullington/react-d3#200]
The option for subcharts with data points included - for line graphs.

**Comment by MatthewHerbst** [comment]
Can you give an example? I'm not sure I'm familiar with this concept.

**Comment by danpatnate** [comment]
Note: This mockup is the desired behavior.
Like the screenshot below (top chart is the main chart with data points, the bottom is the subchart which "should" include data points to reflect it's parent): 
![screen shot 2015-05-06 at 9 12 31 am](https://cloud.githubusercontent.com/assets/3934077/7497597/4e4eb468-f3d0-11e4-9281-92e74b97c989.png)

**Comment by MatthewHerbst** [comment]
How is this different from simply having a second LineChart where the data provided to that chart is just the subset of the part of the parent you want to show?

**Comment by danpatnate** [comment]
@MatthewHerbst I suppose it is similar. The data in each chart is identical, however, the 'subchart' provides the zoom and scrolling capabilities for the large/parent chart - I'd like to keep this behavior. 
I simply would like to add circles on the subchart lines.

**Comment by esbullington** [comment]
Thanks for your suggestion.  I don't think this type of feature is something we're planning (we've already got a lot planned but unimplemented).  But you're more than welcome to use any of our chart components to build this for yourself.

**Comment by danpatnate** [comment]
@esbullington Sure and thank you for the response.
