### ISSUE TITLE
Is line on line chart needs animation

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#205]
@esbullington While thinking how to solve this, I start to think about the reason to animate the whole line in line chart.  There is rarely a case where we need to animate line when points on it are hovered. I start to think we can implement something like [metrics graphics](http://metricsgraphicsjs.org/examples.htm#multilines). 

That's is, when a point on a line is hovered
 * the point is highlighted
 * tooltips (maybe later)

**Comment by esbullington** [comment]
No, I totally agree.  Stylistically, I do prefer the line animation, but it causes too much extra complexity, so let's dump it.  The metrics graphics approach is perfectly fine.

Are you working on this?  If not, I may be able to do it today.

**Comment by yang-wei** [comment]
@esbullington Not for now. I am working on other charts animation.

**Comment by MatthewHerbst** [comment]
@yang-wei I think that tooltips option is very powerful, especially on multi-series graphs such as a multi-series line graph. I really like how it's done in [`react-d3-components`](https://github.com/codesuki/react-d3-components)

**Comment by yang-wei** [comment]
> I totally agree. Stylistically, I do prefer the line animation, but it causes too much extra complexity, so let's dump it. The metrics graphics approach is perfectly fine.

Will take over this.
