### ISSUE TITLE
Expose angleBegin/angleEnd for pieChart

### ISSUE THREAD

**Issue by r-tock** [esbullington/react-d3#216]
For building guage charts that say begins at 225deg and ends at -45deg

**Comment by yang-wei** [comment]
@r-tock 

https://github.com/esbullington/react-d3/blob/master/src%2Fpiechart%2FArc.jsx#L40

You can passed in `startAngle` and `endAngle` as props in piechart. Does this solve your problem?

**Comment by r-tock** [comment]
I can only seem to use 0.31 version (that is the default I get when npm installing) and the following does not seem to work for me.
                         <PieChart
                            data={pieData}
                             colors={self.getColor}
                             startAngle={225}
                             endAngle={-45} />

**Comment by r-tock** [comment]
And it looks like the startAngle comes from the output of pie() method, not from the PieChart props.

**Comment by yang-wei** [comment]
yes looks like I misunderstood what your mean. It's true that we currently do not support this feature =(

This feature is a must have and we welcome your pr =)

**Comment by r-tock** [comment]
When is the next planned release for react-d3. Will you only be supporting es6 going forward?

**Comment by yang-wei** [comment]
Please look at our [roadmap](https://github.com/esbullington/react-d3#roadmap).

Yes we are pretty excited about es6 but you can write es5 code if you want.

**Comment by yang-wei** [comment]
Currently we do not plan to support this feature. 

Close due to inactive. Please open a new issue to make further discussion.

**Comment by yang-wei** [comment]
gi
