### ISSUE TITLE
ScatterChart tests failing on master

### ISSUE THREAD

**Issue by MatthewHerbst** [esbullington/react-d3#222]
After adding the missing props discussed in #218 , I tried to run the tests locally and they failed. Specifically, line 62 of `scatterchart-tests.js` failed with the error:

```
ScatterChart circle color is different from other series FAILED
	AssertionError: expected '#3182bd' to equal '#6baed6'
```

I haven't made any changes to `ScatterChart` locally so I wasn't sure why it was failing. I switched to master and ran the tests there and they still failed! Clearly, something somewhere shouldn't have been merged. The last major changes to `ScatterChart` and the tests for it come from @yang-wei 's #208 . I'm not sure if this problem is due to that or to some other more recent change. I would think it's more recent, otherwise, all the tests since then would have failed too.

**Comment by yang-wei** [comment]
> I switched to master and ran the tests there and they still failed!

@MatthewHerbst Are you on the latest master?
