### ISSUE TITLE
className prop for BasicChart

### ISSUE THREAD

**Issue by jeans11** [esbullington/react-d3#225]
Hi guys !

When we use **BarChart**, we can't specify className prop for **BasicChart** render. Indeed, there is a class for svg element but there isn't class for div element which contain h4 title and svg chart.

**Comment by MatthewHerbst** [comment]
I'll have a pr with these changes + a bit more soon.

**Comment by MatthewHerbst** [comment]
@jeans11 If you look at #227 , while I don't allow you to pass in the className for every sub-component (it would mean adding a massive number of top-level props which we are trying to avoid right now), every Chart, Axis, Title, and Label component will now have a unique className that you can access. That should solve anything you need to do - let me know if you see anything missing.

**Comment by jeans11** [comment]
@MatthewHerbst, thanks !!! I will test it !!!

**Comment by jeans11** [comment]
Hi,

@MatthewHerbst, I can finally test this ! To retrieve the changes, should I change the source of the npm package ?

**Comment by MatthewHerbst** [comment]
The code in the npm package is actually going to be the compiled js if I'm not wrong. Assuming you are using something like `browserify` and `reactify` to compile your JSX into JS, you should probably be alright doing a straight out replace of the code. You might have to do it outside the npm package though, not sure. Let me know how it goes!

**Comment by jeans11** [comment]
Hi,

Thanks @MatthewHerbst. So, I have clone this repo in a thirdparty folder. I use webpack. I meet a little mistake. I think, a dependency is forgotten in the file **LegendChart**  because in line **31**, there is:

```javascript
colors: d3.scale.category20c(),
```
But there is not ```require('d3')```

**Comment by MatthewHerbst** [comment]
Hi @jeans11 . You are completely right, it was accidentally forgotten there - show you how poor our testing currently is :(

For your code to work you can add it in.

Do you want to make a pull-request for the fix? Always nice to have more contributors :+1:

**Comment by yang-wei** [comment]
just curious why there are no errors for this issue

**Comment by MatthewHerbst** [comment]
Because all the charts pass in colors to `Chart` which passes it to `LegendChart`. Since they all pass them in, the `defaultProps.colors` was never getting used, and we don't have a test case for it explicitly, so it probably is failing in the background and we just never noticed.

**Comment by jeans11** [comment]
Hi guys !!

I 'm testing add className to **BarChart** component. I see that **BasicChart** have two classNames defaults props. (_titleClassName_ for h4 element and _className_ for the div container). Good !! but it's not possible to propagate this classes from **BarChart** to **BasicChart**.

**Comment by yang-wei** [comment]
hmmm... so you want a custom className for Basic Chart? yes you can't do that.

**Comment by parshap** [comment]
Has there been any consideration in removing the wrapping `<div>` element and returning just an `<svg>` element when not using a legend? There doesn't seem to be much value in rendering the container and `<h4>` since users may want their own styling, layout, or a different heading element and we will have to manage an API to support all of that. Seems simpler to just move that concern to the end-user.

@jeans11: You can always wrap the chart in your own `<div>` with the class you need.

**Comment by MatthewHerbst** [comment]
@jeans11 is there a reason that the default class names aren't ok for you to use?

@parshap the goal of this library is to make is trivial to create graphs, and having titles is a valid part of that. I agree we should make it easier to modify that title. However, if you want your own, then just don't include a title when you create the graph. Then you can wrap it how you want. I'm not sure how us wrapping the two together hurts you other than you potentially having an empty `<h4>` in your DOM.

**Comment by jeans11** [comment]
Hi guys !

@parshap, this is what i have done ^^.

**Comment by MatthewHerbst** [comment]
Something that could be done could be to move the title element (the `<h4>`) into its own function within the component. Then, when calling for it, if the title is `''`, we could return null which would render a `<noscript>` tag which would have the desired effect I believe.
