### ISSUE TITLE
Updating the npm package

### ISSUE THREAD

**Issue by formula1** [esbullington/react-d3#226]
https://www.npmjs.com/package/react-d3 was last updated 2 months ago

- https://github.com/esbullington/react-d3/pull/198

I can always make this repository directly be required, however I'd prefer not to as I don't know when a change/merge will be breaking

I know this is still in alpha state so more than likely merges will be for stability purposes. You can also add something like below to the index.js

```
console.warn(
  "This Package is in an alpha state and is in active development. "+ 
  "It should be depended on from the git repository: "+gitRepo+". "+
  "See https://docs.npmjs.com/files/package.json#git-urls-as-dependencies for more details"
);
```

This would let people be aware of what they are installing and where they should install from.

**Comment by MatthewHerbst** [comment]
I think it will be upgraded once @esbullington releases v0.4, since there are currently breaking changes in master that would not allow for a minor upgrade. Maybe a better question is what the timeline for v0.4 looks like.

**Comment by yang-wei** [comment]
@formula1 Give us another week. It will be released when animation for each chart are done.

**Comment by formula1** [comment]
@MatthewHerbst That makes sense
@yang-wei No problem, I can tell this library has alot of potential already. Feel free to take your time to do it right, don't rush on my account :)
