### ISSUE TITLE
ColorAccessor's future

### ISSUE THREAD

**Issue by MatthewHerbst** [esbullington/react-d3#237]
So, I've been giving more thought to colors and our graphs, and come to this realization: we either need multiple` colorAccessor`s for different parts of the graph, or, each `*Chart` needs to define its own `colorAccessor`.

Let me explain:

The current design goal (not what it currently is) of `colorAccessor` is:

```javascript
colorAccessor: (series, d, seriesIdx) => seriesIdx
```

That looks fine, except it falls apart if you try to use it for both say, `AreaChart` and `ScatterChart`. That because the `AreaChart` (or `LineChart`) both have something a ScatterChart doesn't have - lines. This is important, because right now the `colorAccessor` assumes that it will have access to each datum (datapoint in the `values` array. However, that is not how lines work. Lines are made up of two points, and thus, to properly color a line segment, `colorAccessor` would need access to both points that makes up that segment.

In addition, the way we implement colors right now is somewhat limiting. For example, I might want to create a `LineChart` where segments above a certain value are one colors, and segments below that value are another. This is not currently possible. It is also not currently possible to say, create a horizontal gradient `AreaChart`.

So, to the solutions:

**1)** We could continue to use a single `colorAccessor` and simply null out values that we can't give you. This option is by far the easiest to implement, though would require documentation (and the user to look at said documentation and/or examples) to know which data parts were available.

**2)** We could move `colorAccessor` out of the common mixin and implement it within each `*Chart`. This is the next easiest solutions, and allows the user full control over colors with minimal code changes from us. However, the downside to this is more code to maintain, and, over time if we are not careful it could become very different to color one chart from the next.

**3)** We could create three common accessors. If you think about any `*Chart`, they are all made up of the same things: lines and/or points and/or areas. Thus, if we had a common color function to handle each, we could keep them in the mixin yet every `*Chart` would still have full access to all color features. This is a slightly bigger code change, but I am happy to do it. The three accessors would be (obviously, some `*Chart` would not use all three:
```javascript
// Where d is the single data point that defines the point
pointColorAccessor: (series, seriesIdx, d, dIdx) => seriesIdx

// Where p0 and p1 are the two points (each with values x,y) that define the line segment
lineSegementColorAccessor(series, seriesIdx, p0, p0Idx, p1, p1Idx) => seriesIdx

// Where p0 and p1 are the two points (each with values x,y,y0) that define the area segment
areaSegmentColorAccessor(series, seriesIdx, p0, poIdx, p1, p1Idx) => seriesIdx
```

I am greatly in favor of the third option. It keeps the overall code cleaner I think, and also enables the most powerful coloring abilities.

Please let me know your thought. I realize that some of this gets a little complex, but imho, there is nothing more powerful to a charting library than the ability the color that charts exactly how you want to.

**Comment by yang-wei** [comment]
Is this implementation going to change how we are using it currently.
Can you explain how are we going to use the others parameter passed in

```js
// currently we are doing
fill={props.colors(props.colorAccessor(point, idx))}
```
This `fill` prop will be passed down to elements like `rect` etc.

// if this feature was implemented like you suggested, what are we going to use p0, p1?
areaSegmentColorAccessor(series, seriesIdx, p0, poIdx, p1, p1Idx) => seriesIdx

**Comment by MatthewHerbst** [comment]
Yes, this implementation would be a breaking change.

Right now, we use `fill` as the fill for everything - the colors of the lines segments, the colors of the circles/points on a line segment, and the color of areas and bars, etc. What this implementation would do is, just as there would be three accessors, there would now be three fills, one each for points, line segments, and areas respectively.

An example of how to get `p0` and `p1` in `AreaChart` would be:

```javascript
render() {

    var props = this.props;
    var series = props.series;
    var values = series.values;

    var area = d3.svg.area()
      .x((d)=> { return props.xScale(props.xAccessor(d)); })
      .y0((d)=> { return props.yScale(d.y0); })
      .y1((d)=> { return props.yScale(d.y0 + props.yAccessor(d)); })
      .interpolate(props.interpolationType);

    var pairs = [];
    // NOTE: this assumes that values contains at least two elements - which is must to be a valid area
    for(var i = 0, vl = values.length; i < vl - 1; ++i) {
      pairs.push([{v: values[i], i: i}, {v: values[i+1], i: i+1}]);
    }

    var areaContainers = pairs.map((pair, idx) => {
      var path = area([pair[0].v, pair[1].v]);

      return (
        <AreaContainer
          fill={props.colors(props.areaColorAccessor(series, props.seriesIndex, pair[0].v, pair[0].i, pair[1].v, pair[1].i))}
          hoverAnimation={props.hoverAnimation}
          path={path}
        />
      );
    });

    return (
      {areaContainers}
    );
  }
```

**Comment by yang-wei** [comment]
Thanks for you elaboration but I still can't see where to use the `po.v` and why do we need that. Do you mind explain more?

I am expecting `props.areaColors` to be color palettes like `d3.scale.category10()`
So,
```js
props.areaColors=d3.scale.category10();
p.range().length //10
p(1) === #1f77b4;
p(2) === ##ff7f0e;
p(1, otherArgs) === #1f77b4;
```
So it means we only need one unique parameters.
```
var fill = props.areaColors(props.areaColorAccessor(props.seriesIndex));
```
seems to be enough to make thing work.
Each point(or area) only need an series id to know which series they are belong to.

Correct me if i am wrong.

**Comment by MatthewHerbst** [comment]
Sorry! Didn't see your above comment until just now.

The `p0` and other points are created by the various `stack` and `area` functions that we use throughout the code. Those functions work by defining a set of boundary points.

What you have above works if you want to limit users to only coloring based on the seriesIndex. I want users to be able to access all the information available at the time of coloring. That includes that coordinates and/or points of the thing being colored. It also includes any additional props that the user has given their series and/or data points.

**Comment by yang-wei** [comment]
The thing I don't like about this API is the complexity it brought. 

> What you have above works if you want to limit users to only coloring based on the seriesIndex

I really think this is what people need to color their graph.
Could you show me one use case where people need to color their graph by coordinate point or additional props.

**Comment by MatthewHerbst** [comment]
I personally have a LineChart where I color the line segments based on the value of the two points. I also have several charts where I color the series based on an id I have assigned them prior to graphing them. Dropping the coordinate and point complexity I'm not in favor of but can understand. But users should absolutely be able to pass arbitrary props in with series and/or datapoint values and be able to access those props at coloring time - that's the reason `colorAccessor` exists in the first place.

**Comment by yang-wei** [comment]
I am ok with what you suggest. This is a great feature but it need a good documentation.
```
pointColorAccessor: (series, seriesIdx, d, dIdx) => seriesIdx
lineSegementColorAccessor(series, seriesIdx, p0, p0Idx, p1, p1Idx) => seriesIdx
areaSegmentColorAccessor(series, seriesIdx, p0, poIdx, p1, p1Idx) => seriesIdx
```
I am good with the default return value(seriesIdx).

Btw one really use case which is really useful I can think of colorAccessor is:
Try to think a single series bar chart where x axis is date and y axis is temperature. Let's say for those date which has high temperate( > 35 c) we want to give it color red, moderate temperature ( 25 < t < 35 ) we give it blue ... etc

**Comment by MatthewHerbst** [comment]
Yeah, I will make sure to make very good documentation. I'll try and push the changes this weekend when I get time. The only chart that doesn't work to have the `seriesIdx` as the return value is `BarChart` as we've seen in #241

**Comment by yang-wei** [comment]
close due to inactive
