### ISSUE TITLE
Composable Charts

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#238]
There are [multiple](https://github.com/esbullington/react-d3/issues/209) [references](https://github.com/esbullington/react-d3/issues/54) [...](https://github.com/esbullington/react-d3/pull/9#issuecomment-66976230) to creating composable charts. I agree with that approach and it was one I also had proposed earlier.

I understand @esbullington has been quite busy with work, and @yang-wei has been doing an excellent job of maintaining and addressing issues. I do have to point out that the pace of development has slowed down, so I am taking this opportunity improve the pace.

Some of the benefits of creating DIY charts I can think of

- It is DIY, so user can add their own custom `svg` elements and stick them in
- reduce the number of props sent to the Top component
- Users can implement click handlers for any supporting component

Seeing the recent development in some libraries (read [redux](https://github.com/gaearon/redux), [react-motion](https://github.com/chenglou/react-motion)) and taking inspiration from them I am thrilled at this possibility. Also the [stockcharts](https://github.com/rrag/react-stockcharts) (cough shameless plug) library does this, and I have some learning from there.

**Comment by yang-wei** [comment]
Yes as you known we had been discussing this for so long but haven't came out with a nice API. I am happy to hear the idea =)

Your library looks really great. 

Just one thing, our library came out first to help user build powerful graph *quickly* with react.
Thus I would also like to keep the current high level api for doing that. 

But I do believe as long as those composable components are built, high level api isn't anything difficult.

**Comment by rrag** [comment]
> But I do believe as long as those composable components are built, high level api isn't anything difficult.

Sure, we can maintain the high level api, My preference is maintain it for backward compatibility but deprecate it. Supplement these by having multiple examples and a good documentation.

My thoughts on this composable api. I see 2 broad categories of charts

### Charts w/ Axis
- Line
- Area
- Histogram, stacked,
- candlestick
and any combination of the above

### Charts w/o Axis
- Tree
- Pie
- gauges
you get the idea...

I am thinking a lot of code reuse for charts which have axis, and those w/o axis need to give more thought on how to categorize them further,

so for Charts w/ axis the user should be able to create a chart by just creating a component with this in the `render`
```
<AxisChart width={...} height={...} data={...} />
  <DataSeries seriesName={...}>
    <XAxis ... />
    <YAxis ... />
    <LineSeries />
    <AreaSeries />
    <ToolTip ... />
  </DataSeries>
  <DataSeries seriesName={...} >
    <YAxis ... />
    <Histogram />
  </DataSeries>
  <Legend />
  <EventHandlerVornoli />
</AxisChart>
```

for Charts w/o axis something like

```
<NoAxisChart width={...} height={...} data={...} />
  <TreeDataSeries groupBy={...} onClick={} colorAccessor={...} >
    <ToolTip ... />
  </TreeDataSeries>
</NoAxisChart>
```

Other ideas welcome

**Comment by esbullington** [comment]
Thanks, @rrag You're absolutely right, composable charts is very much where I wanted to end up, as opposed to front-loading the main chart element with properties.  But I've not adequately documented this part of the project, and need to do some things to promote it better.

I've got some free time now, so I'll take a look at the projects you mentioned as well as see what you've done in `react-stockcharts` since I last took a look -- quite a bit I'm sure!  Are you OK with me mentioning `react-stockcharts` in our README now as a similar project?

**Comment by rrag** [comment]
> But I've not adequately documented this part of the project, and need to do some things to promote it better.

I am not sure I understand that, we do not have a means of composing charts now. And expecting users to write boilerplate code to flatten objects and calculating scales to pass it down is just not an option.

I expect composable charts in react-d3 to be simple in complexity as all the data is provided by the user. You will get an idea when you see the examples on stockcharts

stockcharts was a different animal (and I am glad I took your advice to make it as a separate project) since there are transformations and indicators which are to be calculated by the chart. but regular charts take data provided by the user, and possibly no further transformations are needed

> Are you OK with me mentioning react-stockcharts in our README now as a similar project?

OK? I will be honored. Thank you

**Comment by rrag** [comment]
wanted to share a project I just came across using declarative JSX syntax https://github.com/FormidableLabs/spectacle quite neat

**Comment by yang-wei** [comment]
@rrag After been thinking for quite a while, I think I had came to conclusion regarding to this issue.
We will keep the direction we are currently doing  - which is to provide a quick chart, where user just have to pass in props at top level to get the chart done. In addition, we will export all the components so that user get to build their custom chart.

**Comment by rrag** [comment]
that is fair @yang-wei . I was interested in pursuing this further, but not able to spend the time.

**Comment by yang-wei** [comment]
its ok. Thanks for your input.
