### ISSUE TITLE
Next version - Wishlist

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#239]
- [ ] Composable charts (https://github.com/esbullington/react-d3/issues/238)
- [ ] If animations are needed explore possibility to depend on `react-motion`
- [ ] Use `babel` instead of `react-tools` & `React.Component` syntax instead of `React.createClass`

**Comment by yang-wei** [comment]
Thanks for opening up issue. I had been doing some other project so the development is getting slow.

`babel` had been proposed earlier in #174 and I think we need to do it soon for cleaner syntax (es6 class), es6 module loader etc.

**Comment by askmatey** [comment]
`react-motion` should not be added, please keep this library as simple as it is.

**Comment by vladnicula** [comment]
I would also prefer not having react-motion in this...

**Comment by kidwm** [comment]
How about using [react-faux-dom](https://github.com/Olical/react-faux-dom)?

**Comment by nightlyop** [comment]
I also don't like the idea for including `react-motion`. Before including a bunch of new stuff I think it would be great if someone could cleanup what is available and maybe restructure everything. It is not as much fun as coding new features but I think it is necessary.

**Comment by SylarRuby** [comment]
- The ability to mouseover any value to show actual label amount.

**Comment by yang-wei** [comment]
@SylarRuby https://github.com/esbullington/react-d3/pull/287 is this what you are looking for?

**Comment by dmavrin** [comment]
Hey. First i want to thank you guys for doing great job on this implementation of d3 into react. I just wanna know, when will you release next version with tooltips?

**Comment by yang-wei** [comment]
@dmavrin Thanks. Because I am not the owner of npm, so I cannot publish npm package.

I will create a new npm package with latest release around next week. =)

**Comment by yang-wei** [comment]
@dmavrin I release but it's not fully tested yet so I havnt document it. Let me know if its stable https://www.npmjs.com/package/rd3

**Comment by dmavrin** [comment]
Cool. Will test it as soon as i can. Thanks.
