### ISSUE TITLE
How does colorAccessor work?

### ISSUE THREAD

**Issue by dennisjac** [esbullington/react-d3#244]
From the code it looks like I could use colorAccessor to define a function that for example extracts the color value for a segment for a pie chart from the provided data e.g. by providing a color attribute in addition to label and value.
When I pass a function though this function is never called. I managed to get the "colors" property to work but that apparently only gets the index of the current segment and not the data.
So how exactly can colorAccessor be used?

**Comment by MatthewHerbst** [comment]
`colorAccessor` passes a value (ideally expected to be a primitive type) to the `colors` function. It is the `colors` function that actually determines the color that is generated from the passed-in value. The default `color` function is to use the d3.js `d3.scale.category20c()`.

The current `colorAccessor` function is passed two parameters, `d`, and `idx`. This generally corresponds to the passing the `series` and the `seriesIdx`.

So, a full call looks like:

```javascript
series.map(function(series, idx) {
  ...
  var fill = props.colors(props.colorAccessor(d, idx));
  ...
});
```

The default return value from `colorAccessor` is `seriesIdx`. In practice, what this means is that each series should get its own unique color based on the order they were passed in. However, let's say that you assigned each series a unique id (I do this in some production code I run). If you wanted the color of the series to be based on its unique id, you would want to pass-in a new `colorAccessor` in the form of:

```javascript
function myColorAccessor(series, idx) {
  return series.id;
}
```

There is currently inconsistant usage of `colors` and `colorAccessor` on some of the graphs. Most of that is my fault from when I first designed `colorAccessor`. I'm working on a fix for this based on #237 . I'm hoping to have it in place this weekend  for a pull-request. In addition to the code changes, I will write extended documentation about how to use it, something that is currently lacking.

Does that help?

**Comment by dennisjac** [comment]
From what it looks like the colorAccessor is just ignored:
```
    myColors: function(idx){
        console.log('a');
        return ['#408E2F','#2F4073','#AAA439','#AA3C39'][idx];
    },
    myColorAccessor: function(series,idx){
        console.log('b');
        return 0;
    },
...
<PieChart
  data={pieData}
  width={400}
  height={400}
  radius={100}
  innerRadius={20}
  colors={this.myColors}
  valueTextFormatter={val=>'$'+val}
  colorAccessor={this.myColorAccessor}
  title="Pie Chart"
/>
```
The PieChart gets rendered with the colors specified in myColors() but myColorAccessor is never called and I see no errors in the console.
I also tried to set the valueTextFormatter using an example found here:
https://github.com/esbullington/react-d3/pull/190
but this seems to get ignored as well.

**Comment by MatthewHerbst** [comment]
Strange. It's getting passed correctly as far as I can tell, and it is call on line 50 of src/piechart/DataSeries.jsx:

```javascript
fill={props.colors(props.colorAccessor(props.data[idx], idx))}
```

Is your PieChart getting the correct colors, or is every part of the pie the same color?

**Comment by dennisjac** [comment]
Yes the colors are returned correctly. I see 'a' appearing four times in the output because there are four series in the dataset and each gets one consecutive color from the array defined in myColors as expected. I don't see any 'b' printed in the console though which leads me to believe that the accessor is never called at all.

**Comment by dennisjac** [comment]
I found the reason. I used "npm install react-d3" for installation but apparently that version is outdated and there the fill line doesn't use the accessor. 
What is the release policy here? On Github I see the latest version tagged as 2.0 from February but the npm page claims to deliver 0.3.1 (which is still 4 months old):
https://www.npmjs.com/package/react-d3

**Comment by dennisjac** [comment]
I was able to install the master branch directly from github though with two issues:
a) I now need to include it using require('react-d3/src') instead of just require('react-d3')
b) Apparently due to the use of arrow function react-d3 now requires ES6 support i.e. one needs to use Babel or similar tools to get it working. Is that intentional? I don't see this requirement mentioned anywhere in the README.

**Comment by MatthewHerbst** [comment]
I can't say much in terms of release cycle. @esbullington and @yang-wei can answer more to that. I know we are trying to prep for one soon though.

You should build the project. That will create the proper folder structure with the compiled code.

`gulp build` to just perform a build
`gulp release` to perform a release build

See `gulpfile.js` for all the tasks.

As you continue to point out, we need to really up our game on documentation. Thanks for keeping us to task! :)

**Comment by yang-wei** [comment]
> Babel or similar tools to get it working. Is that intentional? I don't see this requirement mentioned anywhere in the README.

This project is written in ES6 but after you build it you can write it in ES5 as well. So my advise is to build it and keep using
```
var rd3 = require('react-d3')
```

**Comment by dennisjac** [comment]
I can build a new release but I'm not sure how to integrate the files produced in the build directory so that a require('react-d3') would pick them up. The package.json references src/index.js as main so I assume the require would pick up that file and not the ones produced in the build directory or am I wrong about this?

**Comment by parshap** [comment]
@dennisjac We've had similar issues while maintaining and using a fork. The approach we've taken is to always run `gulp release` after making changes, check in the `dist/` directory into git, and update package.json to point to `build/cjs/index.js`. This allows us to install and use our fork as a git dependency with npm.
