### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#248]
http://esbullington.github.io/react-d3-website/

**Comment by bbirand** [comment]
:+1:

**Comment by anthonyray** [comment]
having the same problem here !

**Comment by yang-wei** [comment]
ping @esbullington

**Comment by jaceechan** [comment]
@esbullington  the same problem here

**Comment by e-monson** [comment]
:+1:

**Comment by MatthewHerbst** [comment]
@yang-wei maybe you can fork master and put up your own github.io site until @esbullington comes back?

**Comment by dubert** [comment]
:+1:

**Comment by yang-wei** [comment]
@MatthewHerbst That will be good enough. But I am having holiday. Let's see what can I do asap.

**Comment by MatthewHerbst** [comment]
@yang-wei I can do it if you need, just figured it might be better for you too since you are more involved.

**Comment by MatthewHerbst** [comment]
New working demo page: https://reactiva.github.io/react-d3-website/

+vote to close this issue.
