### ISSUE TITLE
Understanding tickArguments

### ISSUE THREAD

**Issue by MatthewHerbst** [esbullington/react-d3#249]
@yang-wei / @esbullington 

Can one of you please explain lines 48-55 of src/common/axes/XAxis.jsx?

```javascript
var tickArguments;
if (typeof props.tickCount !== 'undefined') {
  tickArguments = [props.tickCount];
}

if (typeof props.tickInterval !== 'undefined') {
  tickArguments = [d3.time[props.tickInterval.unit], props.tickInterval.interval];
}
```

Seems to me that we should go with one method or the other, but not both. Maybe I'm confused about this?

**Comment by yang-wei** [comment]
@MatthewHerbst 
Just saw this, sorry. 

I see, from what I understand we do support time unit x axis. So these codes make sure we convert time properly using `d3.time` method if `props.tickInterval` is defined.
```js
if (typeof props.tickInterval !== 'undefined') {
  tickArguments = [d3.time[props.tickInterval.unit], props.tickInterval.interval];
}
```

**Comment by MatthewHerbst** [comment]
Ah, alright thanks! Just wasn't sure.
