### ISSUE TITLE
Basic Bar and PieChart Examples Error >> Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by AlexHandy1** [esbullington/react-d3#260]
Trying to implement your basic Bar and PieChart examples locally. 
Npm packages all installed correctly - loading up through a basic webpack and bundle.js set-up which had been working fine on previous programme. 
When add in below code to a simple component I get error thrown from underlying react-d3 code of "Uncaught TypeError: Cannot read property 'map' of undefined" (see specific code snippet that throws error at end)
Is the issue how data is being input? Or is it a problem with how bundle.js is compiling the jsx?

````js
var rd3 = require('react-d3');
var PieChart = rd3.PieChart;

var pieData = [
  {label: 'Margarita', value: 20.0},
  {label: 'John', value: 55.0},
  {label: 'Tim', value: 25.0 }
];

var Hello = React.createClass({
    render: function() {
        return <PieChart data={pieData}
              width={400}
              height={400}
              radius={100}
              innerRadius={20}
              sectorBorderColor="white"
              title="Pie Chart"/>
  }
});

//simplified
render: function(){
    return(
          <Hello/>
    )
  }

````

````js
d3.layout.stack = function() {
	    var values = d3_identity, order = d3_layout_stackOrderDefault, offset = d3_layout_stackOffsetZero, out = d3_layout_stackOut, x = d3_layout_stackX, y = d3_layout_stackY;
	    function stack(data, index) {
	      if (!(n = data.length)) return data;
	      var series = data.map(function(d, i) {
	        return values.call(stack, d, i);
	      });
//error here
	      var points = series.map(function(d) {
	        return d.map(function(v, i) {
	          return [ x.call(stack, v, i), y.call(stack, v, i) ];
	        });
	      });
````

**Comment by yang-wei** [comment]
Yes this is the issue with you data input. Since bar chart is not a multi series (stacked) chart, the data layout should be: 
```
var barData = [
  { 
    "name": "Series A",
    "values": [
      { "x": 1, "y":  91},
      { "x": 2, "y":  90},
      { "x": 3, "y":  95},
      ...
  },
  { 
    "name": "Series B",
     "values": [ ... ]
  }
  ...
];
```

Reference: https://github.com/esbullington/react-d3/wiki/Bar-Chart

**Comment by AlexHandy1** [comment]
Thanks - that sorted it, should probably update the other documentation on the JSFiddle

**Comment by steffi-xavier** [comment]
hi i got an error piechart.js:53475 Uncaught TypeError: Cannot read property 'map' of undefined.
here is my code. help me ...

const pieData = [

  {label: 'steffi', value: 20.0},
  {label: 'archana', value: 55.0},
  {label: 'Tamil', value: 25.0 },
  {label: 'surya', value: 25.0 }
]

  ReactDOM.render(
    <PieChart
  data={pieData}
  width={400}
  height={400}
  radius={100}

  innerRadius={20}
  sectorBorderColor="white"
  title="Pie Chart"
/>
, document.getElementById('data_pie')
  )
