### ISSUE TITLE
marker

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#261]
A sneak peek of current implementation. Thanks @nightlyop
Marker only applied to 2 charts:
 * scatter chart
 * line chart

![image](https://cloud.githubusercontent.com/assets/5494874/9835974/c0673900-5a3f-11e5-89f4-0ca1a4a3cdd2.png)

How to use (API):

![image](https://cloud.githubusercontent.com/assets/5494874/9835986/039f5e3c-5a40-11e5-9bbf-a897020c0a2c.png)

Implementation was good but I did not happy with the api because I think data should be pure data. To me, thing like `markerOuterRadius`(from above) seems like a component property.

What api should look like: 
```
// image we have data as picture above
<ScatterChart
  data={scatterData}
  marker={["rect", "star", "circle"]}        <- pass in marker we want 
/>
```
*if marker prop length is less than series length, a default marker will be passed in =) *

A more complex marker?
```
// image we have data as picture above
<ScatterChart
  data={scatterData}
  marker={[{marker: "rect", appearance: { width: 5, height: 5, animationFactor: 1.25}},  ... ]}        <- pass in marker we want as object. appearance is used to describe the marker.
/>
```
Hey  @nightlyop if you have some spare time, would like to know what do you think. You can see the branch I am working at [here](https://github.com/esbullington/react-d3/tree/DataPointSymbols-cleanup)

Todo list:
##### fundamental
 * [x] marker mixin
 * [ ] new api
 * [ ] documentation related to marker
 
##### add on
 * [ ] custom marker

**Comment by nightlyop** [comment]
To pass a separated marker object to set the properties of the markers sounds good to me. I like your example for a more complex marker! However, I would not use mixins (https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750 but we discussed that already in another issue).

**Comment by yang-wei** [comment]
@nightlyop Yes I am aware of this. However, I think mixins is really good for code resusablity, I still can't figure out how to replace our mixins with HOC. 

If you look at [react-future repository](https://github.com/reactjs/react-future/blob/master/01%20-%20Core%2F02%20-%20Mixins.js), mixins will be support in other way so I think it's safe enough to use mixins since it makes our codebase simpler =)
