### ISSUE TITLE
Correct combination of react versions

### ISSUE THREAD

**Issue by AlexHandy1** [esbullington/react-d3#262]
I am having some trouble getting the correct combination of react versions to work with react-d3. 

When I use 0.12.1 as in the JS Fiddle and include the CDN link - when I nest a bar chart component (see simple code example at end) I get an "Cannot read property 'firstChild' of undefined" error thrown from react-d3 code.  The cause seems to be that react is trying to render a nested component (the react-d3 bar chart) that is in a different version (https://github.com/facebook/react/issues/2402)

Alternatively, when I try to include a more recent version of React (e.g. 0.13^) I get a different error "inst.render is not a function" which may be caused because it doesn't recognise BarChart in the way it is instantiated through this module e.g. tried to render an element whose type is a function that isn't a React component.

What version of React is this link using ( <script src="https://cdn.rawgit.com/esbullington/react-d3/fff663d549c9492ecf7da3a4108718b04630432a/dist/public/js/react-d3.min.js"></script>)?

Its been unusually hard to build basic working examples so great to get some clarity on this.

Example with 0.12.1

````
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello React</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.12.1/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.12.1/JSXTransformer.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.rawgit.com/esbullington/react-d3/fff663d549c9492ecf7da3a4108718b04630432a/dist/public/js/react-d3.min.js"></script>
  </head>
  <body>
    <div id="chart"></div>
    <script type="text/jsx">
        var BarChart = rd3.BarChart;
        var data = [
          {label: 'London', value: 5},
          {label: 'Tokyo', value: 6},
          {label: 'Lagos', value: 7}
        ];
        var ChartArea = React.createClass({
          render: function(){
            return(
            <ChartType data={data}/>
          )}
        });
        var ChartType = React.createClass({
          getInitialState: function(){
          console.log("loaded")
            return{
             data: this.props.data
            }
          },
          componentDidMount: function(){
            console.log("mounted")
            var apiString = "http://api.openweathermap.org/data/2.5/weather?q=London,uk"
            $.ajax({
              url: apiString,
              type: 'GET',
              dataType: 'jsonp',
              success: function(data) {
                this.setState({
                  data: [{label: 'London', value: (data.main.temp) - 273.15},{label: 'Tokyo', value: 6},{label: 'Lagos', value: 7}]
                });
              }.bind(this)
            });
          },
          render: function(){
            return(
              <BarChart data={this.state.data}
                        width={500}
                        height={200}
                        fill={'#3182bd'}
                        title='Temperatures'/>
            )
          }
        });
        React.render(<ChartArea/>, document.getElementById("chart"));
    </script>
  </body>
</html>
````

**Comment by nightlyop** [comment]
I don't get it. You create a component `ChartArea` which contains a component `ChartType` and the component `ChartType` contains a `BarChart`?

Do the examples given in `docs/examples/main.js` work with your React version? You could copy them into your page to give that a try.

**Comment by AlexHandy1** [comment]
@nightlyop thanks for getting back to me, neither working with any kind of dynamic state. 
Have moved onto something else so will close given this would unlikely ever be an actual production set-up
