### ISSUE TITLE
React v0.14

### ISSUE THREAD

**Issue by TannerRogalsky** [esbullington/react-d3#265]
Hello maintainers! I have good news for you! In the general case, this library seems to just work without any changes.

However, at the time of v0.14-rc1, a bunch of tests break because of some weird behaviour around SVG DOM nodes having an object instead of a string for a className attribute when you pull them out of the render tree. If that sounds weird it's because it is and I'm not 100% on what's up. Nor am I sure you should worry about it because it seems like an edge case in React that may be solved by release. Just didn't want you to be blindsided by this.

Thanks for the lib!

**Comment by yang-wei** [comment]
Thanks for the notice. Really appreciate =)

**Comment by TannerRogalsky** [comment]
:+1:
