### ISSUE TITLE
"TypeError: d is undefined" when values is an empty array

### ISSUE THREAD

**Issue by nhjk** [esbullington/react-d3#267]
For example:

```javascript
....
var data = [{
  name: 'series a',
  values: []
}];

return <div>
  <LineChart
    data={data}
    height={400}
    viewBoxObject={{x: 0, y: 0, width: 500, height: 400}}
  />
</div>
....
```

The reason I have empty values is that I asynchronously fetch the data from a server, so its empty until the request completes.

**Comment by MatthewHerbst** [comment]
It is an intentional error. You cannot define a line with less than two points of data. You should dynamically add the object to `data` once you have the data to fill it.

**Comment by nhjk** [comment]
That makes more sense. Thanks!

**Comment by MatthewHerbst** [comment]
Glad to help! If you want, feel free to make a pr that gives a better error message :+1:
