### ISSUE TITLE
Transitions?

### ISSUE THREAD

**Issue by Sigfried** [esbullington/react-d3#268]
How do you recommend managing D3 transitions with these charts?

**Comment by MatthewHerbst** [comment]
Can you give any context into what you are trying to do? 

We've had some discussion about animations, but React gets all wonky when it comes to them, and there aren't any really perfect solutions right now.

**Comment by Sigfried** [comment]
Nothing in particular. I'm wondering about the possibility of using D3 in a React context. I know D3 well and React not at all. And I'm wondering if putting D3 into a React component basically means giving up the possibility of transitions. If so, I may just stick with traditional D3 programming--which has various disadvantages.

**Comment by MatthewHerbst** [comment]
You have to do a lot of overhead in React to get it to work nice. If you are new to React, I would focus on either learning React first, or, stick with the traditional D3 programming (maybe take a look at Angular?)

**Comment by yang-wei** [comment]
Did you look at React documentation regarding [animation](https://facebook.github.io/react/docs/animation.html). I think this solution fit this library well. Never gave it a try but if you do in the future, we would glad to have you report it for other users reference.
