### ISSUE TITLE
can't disable labels for piechart

### ISSUE THREAD

**Issue by brycedorn** [esbullington/react-d3#271]
I'm trying to draw a `PieChart` without labels, but both `showInnerLabels={false}` and `showOuterLabels={false}` aren't doing anything. 

looked through src, looks like `props` should be [propogating](https://github.com/esbullington/react-d3/blob/master/src/piechart/Arc.jsx#L52) down from `PieChart` all the way to `Arc` but it looks like the default might be [overriding](https://github.com/esbullington/react-d3/blob/master/src/piechart/Arc.jsx#L29) these values between `ArcContainer` and `Arc`. is this a known bug?

**Comment by MatthewHerbst** [comment]
If that's happening, it's either standard behavior or a bug with React; I've been under the impression that defaultProps is only used when the prop isn't specified at all from the parent, and `{...this.props}` should count as specifying props.

**Comment by brycedorn** [comment]
((didn't realize I was using the other react d3 library, switched to this one & it works :stuck_out_tongue_closed_eyes:))
