### ISSUE TITLE
Specify Custom Scales?

### ISSUE THREAD

**Issue by posgarou** [esbullington/react-d3#272]
I wanted to check up on the status of custom scales (see #185, which was closed due to inactivity).  As noted in the previous issue, this is a pretty important / useful feature.

Are any of the contributors currently working or planning to work on this?  Otherwise, is this PR-able?

Thanks!

**Comment by MatthewHerbst** [comment]
Everything is PR-able! :+1:

**Comment by posgarou** [comment]
@MatthewHerbst Sounds good, I'll try to pull a PR together over the next few days.

**Comment by nightlyop** [comment]
We did this. See: #286
