### ISSUE TITLE
Question: forking and building

### ISSUE THREAD

**Issue by khinlatt** [esbullington/react-d3#275]
@esbullington I attached an onClick handler hook to the pie chart after forking your repo. Since I only did that one type of chart for now, I did not want to create a PR against yours yet.

How can I package the new changes properly so I can refer to my git repo with the new changes?

I am new to npm so it would be great if you can guide me what to do after forking and updating changes to files in /src. I really appreciate it.

Thanks for the module!

**Comment by MatthewHerbst** [comment]
Do you actually want to put the package on npm, or just use it in your code? The easy thing if you just want to use it in your code would be to simply manually include the `react-d3` code that you have instead of taking it from npm.

**Comment by mbrookes** [comment]
```

It depends on whether you're installing as an npm package: 

https://docs.npmjs.com/cli/install

Or creating a dependancy in your parent projects package.json:

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by khinlatt** [comment]
I just want to use it in my code. Yet still want to be able to do like this dependencies: { "react-d3": "git::/mygithub..." } in package.json

I just ended up manually copying the codes from node_modules/react-d3 into a repo, makes changes and then, specify npm to pull from it instead. Thanks.

**Comment by parshap** [comment]
@khinlatt: See this comment for how I've handled this: https://github.com/esbullington/react-d3/issues/244#issuecomment-126530747

**Comment by khinlatt** [comment]
@parshap that was what I was looking for. Thanks for the help!
