### ISSUE TITLE
How do you specify colors for BarCharts?

### ISSUE THREAD

**Issue by eadlam** [esbullington/react-d3#281]
Is there any documentation on how to specify colors for BarCharts?

**Comment by MatthewHerbst** [comment]
Most of the charts use some version of the `colorAccessor` and `colors` props. You can find the source for most of the charts in the [CartesianChartPropsMixin.js mixin](https://github.com/esbullington/react-d3/blob/master/src/mixins/CartesianChartPropsMixin.js). It basically works like this:

`colors` is a function that, given some input, returns a color. The default `colors` function is [d3.scale.category20c()](https://github.com/mbostock/d3/wiki/Ordinal-Scales#categorical-colors).

`colorAccessor` is a function that takes some data and, using that data, decides what value to pass to the `colors` call.

So, while iterating through your BarChart data, the code decides the color by calling:
```javascript
// https://github.com/esbullington/react-d3/blob/master/src/barchart/DataSeries.jsx#L42
fill={colors(colorAccessor(segment, seriesIdx))}
```

The `segment` represents which value is being looked at in a stacked bar chart (a "normal" bar chart is really just a stacked bar chart with a single stack), and the `seriesIdx` represents which bar is being worked on.

There are some known issues with colorAccessor for other chart types, but for BarChart you should have no problem basing the colors off of anything you want.

**Comment by MatthewHerbst** [comment]
Now that you ask, it would be a good idea to get some docs on the example site for this. I was working on an update to `colorAccessor` to fix the known issues, but have been too busy for the last few months to finish it. I'll try and take another look at that in the coming weeks.

**Comment by MatthewHerbst** [comment]
@eadlam please close this issue if the above answers your questions. Let me know if you need any additional clarifications.

**Comment by eadlam** [comment]
Yes, that helps. Thank you!
