### ISSUE TITLE
Problems with VoronoiCircleContainer for LineChart when xAccessor and yAccesor are set

### ISSUE THREAD

**Issue by JeffAMcGee** [esbullington/react-d3#282]
When I create a lineChart with a custom xAccessor and yAccessor, I get the following errors:

    Invalid value for <circle> attribute cx="NaN"
    Invalid value for <circle> attribute cy="NaN"

In https://github.com/esbullington/react-d3/blob/master/src/linechart/DataSeries.jsx#L76 It looks like DataSeries is reading from this.props.value which has already been transformed by xAccessor and yAccessor. The data is being sent through xAccessor and yAccessor a second time.

**Comment by yang-wei** [comment]
You are right. @JeffAMcGee . Had you used it with other charts too?

**Comment by JeffAMcGee** [comment]
I have not tried using xAccessor and yAccessor with the other chart types, so there may be similar bugs there as well.

**Comment by RogerNoble** [comment]
I've run into the same issue - the reason is that the circles are expecting the data property names to be `x` and `y`. The quick and dirty fix is to update your x/yAccessor to look like
```
xAccessor(x){
    return 'x' in x ? x.x : x['actual data property name'];
},
````
