### ISSUE TITLE
Tooltips for data points

### ISSUE THREAD

**Issue by maherbeg** [esbullington/react-d3#285]
Tooltips and formatting for said tooltips would be a great feature to have to make exploring in depth graphs much easier.

An example from rickshaw http://code.shutterstock.com/rickshaw/examples/formatter.html

**Comment by nightlyop** [comment]
That'll be great! Google charts display the selected values similarly: https://developers.google.com/chart/interactive/docs/gallery/linechart
:+1:

**Comment by yang-wei** [comment]
this should be done in master.
