### ISSUE TITLE
react-d3 in 2016

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#289]
Hi folks, merry xmas :santa: 

React-d3 had been active recently(thanks to all those pr and issue) and I will look at it very soon. Although it's not possible to close all issues before 2016 but thanks for the support all the time especially @esbullington (who created this library), @MatthewHerbst @nightlyop @mwhite and all awesome [contributors](https://github.com/esbullington/react-d3/graphs/contributors).

I know some of you are using react-d3 in your project so please don't be shy to add it [here](https://github.com/esbullington/react-d3/wiki).

@esbullington recently create an [organisation](https://github.com/reactiva) for this library but I think it's best to keep the repository here so that many people will see it (higher google search ranking).

Also because this library is getting larger, we will be very happy to add one or two maintainers =) If you are interested please let us know here or dm me though gitter.

**Comment by MatthewHerbst** [comment]
:+1: you're too kind @yang-wei . I'm sorry I've kind of been MIA the last few months. I'm making it a new years resolution to get back to my old level of involvement!

Happy holidays all.
