### ISSUE TITLE
React Native Version!

### ISSUE THREAD

**Issue by dcflow** [esbullington/react-d3#296]
Hi,

Is it possible to make a react native version of this?
What is an estimate percentage of the code base that needs to change?

Thank You!

**Comment by yang-wei** [comment]
@DHidee66 Dude this is an exciting feature but I have to tell you that I never `npm install react-native` and I am currently busy with other thing.

> What is an estimate percentage of the code base that needs to change?

I can't answer this for now but any input will be appreciated.

**Comment by MatthewHerbst** [comment]
:+1:

**Comment by beeant** [comment]
+1

**Comment by nonotest** [comment]
+1

**Comment by crozzfire** [comment]
+1

**Comment by jfbaro** [comment]
+1

**Comment by meabhinav** [comment]
+1
