### ISSUE TITLE
We need to share yDomain between adjacent AreaCharts

### ISSUE THREAD

**Issue by L5eoneill** [esbullington/react-d3#302]
This can be set in vanilla-d3, but our component can't seem to override react-d3 on this issue.

**Comment by yang-wei** [comment]
can you show us some code to elaborate your problem.

**Comment by L5eoneill** [comment]
Our component looks like this:
<AreaChart
          data={graphData}
          width={width}
          height={height}
          colorScale={colorScale}
          margin={margin}
          xAxis={xAxis}
          yAxis={yAxis}
          yDomain={sharedScale} />
Where sharedScale = [0, 240000], for instance.
And the two charts y-axes differ: 
Chart 1 goes 0 to 220000 and Chart 2 goes from 0 to 22000 (losing one order of magnitude), the same as before we added yDomain to the component. So, not using the upper max we send them.

Is the yDomain supposed to be specified some other way? When I checked d3 docs, it appeared this should not be part of the yAxis object.
