### ISSUE TITLE
A valid ReactComponent must be returned.

### ISSUE THREAD

**Issue by dtysky** [esbullington/react-d3#304]
I used react 0.13.3 in my project.
When I debug with grunt, my project worked fine, but after i built all and run it, this error were thrown out:

Invariant Violation XXXChart.render(). A valid ReactComponent must be returned.

It can be fixed after i remove the react-d3/node_modules/react, so i think your module can work fine with react 0.13.3, and not work with react 0.15.9-alpha.1.

**Comment by yang-wei** [comment]
Yes I am aware of the issue. Maybe we shouldn't not set `React` as depedency.

**Comment by MatthewHerbst** [comment]
Or just make sure to specify the version of React we are currently tied to? Seems like the right way to do it.

**Comment by yang-wei** [comment]
https://github.com/rackt/react-redux/blob/master/package.json#L85-L87

**Comment by dtysky** [comment]
@yang-wei 
Thanks.
