### ISSUE TITLE
npm installation of LineChart is not working with `TypeError: Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by blmarket** [esbullington/react-d3#305]
Current npm-released version(0.4.0) of LineChart.jsx does not contains `DefaultAccessorMixins`, which leads to above error.

https://github.com/esbullington/react-d3/blob/1525e7827e7352cf3fcd04b12bbad60cd80a7530/src/linechart/LineChart.jsx

Maybe I can workaround this by using current master branch, but I'd like to see some stable version which can be used instantly. How about to release a fix-version before your 0.5.0 milestone?

**Comment by yang-wei** [comment]
should work now for https://github.com/yang-wei/rd3
