### ISSUE TITLE
how to specify custom color attribute in line chart?

### ISSUE THREAD

**Issue by gnuman** [esbullington/react-d3#308]
Hi 

I am not sure this is a bug or enhancement, I am using multi series in Line chart and i want custom colors for each series.
I specify data as follows :- 
 ```
data={[{
         name: 'comments',
         values: this.props.comments,
         color: 'red'
  }, {
         name: 'likes',
         values: this.props.likes,
         color: 'blue'
 }]}

```
However these values don't seem to get worked, can you please let me know how to specify custom color values?

**Comment by yang-wei** [comment]
Hi you can do that.

Looks at colorAccesor in this [documentation](https://github.com/esbullington/react-d3/wiki/CartesianChartPropsMixin)
