### ISSUE TITLE
missing script: build

### ISSUE THREAD

**Issue by ernest-rhinozeros** [esbullington/react-d3#314]
If I try to run the `minified` script I get the error message:

`npm ERR! missing script: build`

The `scripts` section of the `package.json` looks like this:

```json
"scripts": {
    "env": "env",
    "test": "gulp test",
    "watch": "gulp watch",
    "minified": "gulp release && npm run build && NODE_ENV=production browserify -t [ reactify --es6 ] --standalone rd3 ./build/cjs/index.js | uglifyjs -c > dist/public/js/react-d3.min.js"
  },
```

So there is no `build` script and there never was AFAICS (I was looking at the history of `package.json` and apparently https://github.com/esbullington/react-d3/commit/f9f7244458aa0452f0bf0b1dab3ba8ad810c75bf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 introduced the `minified` script but there was no `build` script).

Removing the `npm run build && ` and running `npm run minified` will work and it seems that everything necessary is created but I don't know if I'm missing something.

**Comment by yang-wei** [comment]
> Removing the npm run build && and running npm run minified will work and it seems that everything necessary is created but I don't know if I'm missing something.

You are correct. Mind to send us a pr ?

**Comment by ernest-rhinozeros** [comment]
I don't know if just removing the `npm run build` is alright, but I'll commit the version without it.
@esbullington should know if there's missing something from the `npm run build` script.
