### ISSUE TITLE
Legends should be customizable from parent charts

### ISSUE THREAD

**Issue by LouisTakePILLz** [esbullington/react-d3#316]

**Comment by kaiyuzhao** [comment]
Agree. I am looking for a way to customize the size of font in the legend, but haven't figured it out yet

**Comment by LouisTakePILLz** [comment]
There doesn't seem to be any way as yet; most-derived components rely upon the common `Chart`, but don't relay any extra props.
For instance, LineChart only passes the `legend` bool prop: [src/linechart/LineChart.jsx](https://github.com/esbullington/react-d3/blob/a30200a1249d72c96b8547e134c6d5d9abab47e5/src/linechart/LineChart.jsx)

**Comment by yang-wei** [comment]
will work on this after clean up work done in https://github.com/yang-wei/rd3
