### ISSUE TITLE
LineChart not passing on sideOffset property

### ISSUE THREAD

**Issue by bradtwurst** [esbullington/react-d3#317]
https://github.com/esbullington/react-d3/blob/master/src/linechart/LineChart.jsx#L61-L64

The code 
```
legend={props.legend}
data={props.data}
```

needs an addition property passed on

```
legend={props.legend}
sideOffset={props.sideOffset}
data={props.data}
```

**Comment by yang-wei** [comment]
solve in https://github.com/yang-wei/rd3/pull/7
