### ISSUE TITLE
where can i find the documents?

### ISSUE THREAD

**Issue by p2227** [esbullington/react-d3#318]
the wiki is too simple

**Comment by MatthewHerbst** [comment]
So, make it better? :+1:

**Comment by yang-wei** [comment]
@p2227 How about the unit test ?

**Comment by p2227** [comment]
@yang-wei  you may need jsdoc  https://github.com/jsdoc3/jsdoc

**Comment by yang-wei** [comment]
@p2227 Thanks I will keep that in mind
