### ISSUE TITLE
How to show tooltips in lineChart?

### ISSUE THREAD

**Issue by FezVrasta** [esbullington/react-d3#334]
I can't find the documentation to show them but I see that they should be supported looking at the code...

**Comment by Aleczhang1992** [comment]
@FezVrasta Me too！Even I tried to use as they say.But it didnt work!
`formatTooltip(d) {
        return [
            d.xValue,
            d.seriesName + ': ' + String(d.yValue),
        ].join('<br />');
}`
`<LineChart
          legend={true}
          data={lineData}
          width='100%'
          height={400}
          viewBoxObject={{
            x: 0,
            y: 0,
            width: 1000,
            height: 400
          }}
          xAxisFormatter={(val)=>Common.getTime_ymd_hms("date",val)}
          xAxisTickInterval={{unit: 'day', interval: xInteral}}
          gridHorizontal={true}
          showTooltip={ true}
          tooltipFormat={ this.formatTooltip }
        />`

**Comment by FezVrasta** [comment]
FInd out that they work on the maintained fork and this one is just dead. (checkout `rd3`)
