### ISSUE TITLE
PropTypes Support for React v^15.5.0

### ISSUE THREAD

**Issue by danang-id** [esbullington/react-d3#344]
Since `React.PropTypes` has been deprecated from main `react` library package starting from version 15.5.0 up, wouldn't it will be better to replace `React.PropTypes` with one from the `prop-types` library package?

As example from:
```javascript
var React = require('react');
module.exports = React.createClass({
propTypes: {
    data: React.PropTypes.array,
  }
});
```

Become:
```javascript
var React = require('react');
var PropTypes= require('prop-types');
module.exports = React.createClass({
propTypes: {
    data: PropTypes.array,
  }
});
```

This issue is happening when you are using React from version 15.5.0 up. This example taken using React version 16.0.0.
![image](https://user-images.githubusercontent.com/27526130/32645224-cc958154-c618-11e7-92cc-0d2ed950f7f3.png)

**Comment by SoundBlaster** [comment]
@danang-id Why is this issue closed? I install this module from npm and I have error with React 16
```"react": "^16.2.0",```

**Comment by danang-id** [comment]
@SoundBlaster I didn't read the [README](https://github.com/esbullington/react-d3/blob/master/README.md) before (sorry, my bad). Yet, I close this issue mainly because of this source is no longer being maintenanced for now. A [new and maintained package](https://github.com/yang-wei/rd3) has been created and maintained by Yang Wei.

Please take a look on the new fork. This issue, as well as many other issues, has been solved there.

**Comment by SoundBlaster** [comment]
@danang-id ok, good.
