### ISSUE TITLE
Are you planning to support `es6`

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#51]
Because I saw there es6 is set to true in browserify setting :D
```
"browserify": {
        "transform": [
            ["reactify", {"es6": true}]
        ]
   }
```

**Comment by esbullington** [comment]
Yes, right now you can use any ES6 feature supported by reactify:  arrow functions, rest params, templates, object short notation and classes.  I'm also looking at perhaps adding traceur, so we can have all the ES6 features.

One of my goals is to eventually remove the lodash dependency and use ES5 and ES6 functional features instead.

**Comment by yang-wei** [comment]
Looking forward to this addition @esbullington
