### ISSUE TITLE
Color shader method

### ISSUE THREAD

**Issue by yang-wei** [esbullington/react-d3#52]
Hi @esbullington , I create a new issue for the color shader method which you suggested in #49. What do you think about [this color shader method](http://jsbin.com/direnoqete/3/edit) for the animation method.

**Comment by esbullington** [comment]
Hey @yang-wei this looks great.  If you'd like to go ahead and add this approach to the current PR, I'll merge it.  

And then, if you want, you can submit a separate PR with the Voronoi tesselated overlay to detect mouse events that are nearby each datum node.  The Voronoi might be tricky so let me know if it's taking you too long or if there's something you're having trouble with, and I'll do my best to help.

By the way, I found another example of a Voronoi tessellation used to detect nearby events [right here](http://bl.ocks.org/mbostock/8033015), again by Mike Bostock.   This particular one is for line chart, not a scatter plot, but it's a similar idea (and a good model for whenever we do the line chart animation).

I just opened an issue for the Voronoi tessellation for mouse event detection in #53.

**Comment by yang-wei** [comment]
I will look at #53 when I have time later. Closing this since you merged it =)
