### ISSUE TITLE
Will you support multi types?

### ISSUE THREAD

**Issue by vid** [esbullington/react-d3#54]
really excited by your project. are you planning to support multiple types (eg line + area, or ideally arbitrary combinations) in one chart? Will this include transitions between types? thanks.

**Comment by esbullington** [comment]
Thanks for your comment!  In short, yes.  I've got pretty big plans for this library, which includes both simple "pre-baked" charts like you see in the examples, and a collection of well-documented chart primitives that can be mixed, matched, and composed to make custom charts.  And yes, we'll get transitions basically for free.

**Comment by vid** [comment]
That's excellent. Very glad to hear it.

**Comment by esbullington** [comment]
Actually, even now you should could mix chart types by taking a look at the top-level component of the chart you're interested in, and require the `DataSeries` component of the chart you want to add to it under a different name (e.g., `LineChartDataSeries`) and then stick it beside the `DataSeries` component of the first chart.

Data frame transitions won't happen until probably 0.4.0 or later, but simple chart type compositions should work now.

**Comment by esbullington** [comment]
Since this is on our roadmap, I'm going to go ahead and close this issue.  Please feel free to open another one if you have any other questions/concerns.

**Comment by vid** [comment]
Thanks. I spent a few moments trying to piece it together but considering the pace of change will wait for a provided demo.
