### ISSUE TITLE
Zoom and pan on charts

### ISSUE THREAD

**Issue by rrag** [esbullington/react-d3#72]
I am working on something very similar focused on charts for stocks. I had made some progress and wanted to open source it and came across your work, this is very exciting as it follows the very same technologies.

My work is far from complete so it will be prudent to contribute here rather than open a new project for my work.

Check out what I have done here.
http://react-charts-d3.s3-website-us-east-1.amazonaws.com/

One feature I struggled the most is to create a linear scale with date which is not continuous (see how the x axis dates do not have weekends but still shows up linear) I would like to get your feedback and add that scale also to this project if you agree of course.

Also I have used React style zoom and pan, no d3.zoom or d3.drag behavior which will be a nice addition to this project.

**Comment by yang-wei** [comment]
wow I'm so excited with this addition @rrag ! Great work

**Comment by esbullington** [comment]
Hi @rrag that looks fantastic!  Well done!  These would be a fantastic addition to react-d3, and I'm pleased that you'd consider adding them.

We definitely should join efforts and try to factor out as much of our mutual code as possible to lower-level components, which anybody can then mix and match as needed.

It looks like although you use Bootstrap, jQuery, Font-Awesome, and other libraries for your example page, the only dependencies your chart components appear to have are d3 and React.  Is that correct?  If so, that's great.  I just eliminated our Lodash dependency so our charts only depend on d3 and React, too.  I think it's pretty critical to keep the dependencies limited to React and d3, although of course for example/demo pages additional dependencies are no problem.

It looks like you did your tooltips in pure React.  That's great!  I was about to start on this but I knew it would take a long time to iron out all the edge cases.

I notice you use AMD.  Do you mind commonjs?  That's what we're using at the moment.  We can definitely move to supporting AMD builds in addition to CommonJS if that will help you out (maybe through UMD?).

Does your area chart support stacked series?  I haven't had time to look through the full codebase yet, although I definitely will.

Let me think about how to best organize combining the projects.  It will probably take us a while to figure out where the codebases overlap, and factor that out.  Do you have any suggestions/preferences on how to go about this?

Are you OK with the MIT license?

Also, let me think about the non-continuous issue you mention.  I think I may have a solution to both that and with the problem I was having with creating a Date-friendly API for our charts.  Let me try a few things and I'll post an issue for that.

**Comment by rrag** [comment]
> It looks like although you use Bootstrap, jQuery, Font-Awesome, and other libraries for your example page, the only dependencies your chart components appear to have are d3 and React. Is that correct?

That is right, my vision is once React-d3 has the features needed for my app, I will start using it as a bower dependency. I am also using Reflux.js as a means to send actions and listen to changes from a store, but that would be logic on my app and I don't think it should be included in React-d3

> It looks like you did your tooltips in pure React. That's great! I was about to start on this but I knew it would take a long time to iron out all the edge cases.

yes I have tool tips as

    <svg:text>

I feel that this made my work easy but if you need a floating tool tip (outside the bounds of <svg> ) or one which wraps text, there are other options you will have to consider, my usecase was simple enough for svg text

> I notice you use AMD. Do you mind commonjs? That's what we're using at the moment. We can definitely move to supporting AMD builds in addition to CommonJS if that will help you out (maybe through UMD?).

I want to get out of AMD too, cjs works.

> Does your area chart support stacked series?
Not yet. I was going to work on Simple moving average, exponential moving average and compare with a different stock next. The Compare I am thinking will be tricky so I am keeping that last.

> Let me think about how to best organize combining the projects. It will probably take us a while to figure out where the codebases overlap, and factor that out. Do you have any suggestions/preferences on how to go about this?

I have not used React-d3 enough so I am not sure if my observation is accurate, I don't like I have to use a line chart as

    <LineChart
      legend={true}
      data={lineData}
      width={500}
      height={300}
      title="Line Chart"
      />

This means that the user does not have control of axis, what if I don't want y axis but only x, or I need ticks as grid lines, or I need to have 2 y axis, one on left and one on right. I prefer a syntax like this

    <Chart width={} height={} >
        <XAxis scale={...} orient="bottom" />
        <LineChart
           yScale={} xScale={}
           ...
           ... />
        <AreaChart
           yScale={} xScale={}
           ...
           ... />
        <ScatterChart
           yScale={} xScale={}
           ...
           ... />
    </Chart>

That way I can easily add/remove any data series, and in the event React-d3 does not support something simply add a

    <g>
         <anysvgtag>
             ...
         </anysvgtag>
    <g>

This does expose the xScale and yScale to the user of React-d3, so we need to figure out how they can get them, (may be a mixin which create the x & y scale given the data... just thinking)

> Are you OK with the MIT license?

Yes

Which feature do you prefer I start off first? I was thinking candlesticks so it will be simple for me and get comfortable with, did you check the other advanced chart types in my app? do you see them part of React-d3?

**Comment by esbullington** [comment]
@rrag the more I've thought about it, the more I think that maybe your charts would best go in a specialized react-stockcharts library.  Then, we can both collaborate on a react-components library that contains the basic chart components we're both using.  In particular, we should collaborate on a pure React axes component that we can use in both of our libraries.

After thinking about it some, I would like to limit this chart library to the basic chart types, and probably not include the advanced charts that you've created.  I've also got a different vision for how I'd like to implement tooltips: I'd been planning on keeping the tooltip information static, at the top right of the chart.

That said, I'd be very happy to accept a PR for the candlestick chart, if you're willing to work with me on what I have in mind (for example, we're using d3's `d3.scale.category20c()` [color palette](https://github.com/mbostock/d3/wiki/Ordinal-Scales#category20c) to get a consistent look across charts).  Also, I was planning on keeping tooltips static in the top-right of the charts, something like [MetricsGraphics does it](http://metricsgraphicsjs.org/examples.htm).

But I realize that you've created your own awesome stockchart library, and you may have your own vision for where you want to go with it.

Either way, I hope we can collaborate on a react-chart-components library for basic chart components, including an Axis component, possibly a generalized DataSeries, and other chart components.

**Comment by rrag** [comment]
@esbullington I would agree, stock charts are a more specialized case of charts. I have not seen the MetricsGraphics earlier, and it is interesting to see how they have handled mouse hover of the chart.

I will create a separate stockcharts project on github and add my work there. I will my work on candlesticks over this weekend and send a PR after that.

What do you think of my suggestion to having a chart by piecing together a group of components? I think that will make up the react-chart-components library and it might serve as a dependency to the react-stockcharts when I create it.

**Comment by esbullington** [comment]
>What do you think of my suggestion to having a chart by piecing together a group of components? I think that will make up the react-chart-components library and it might serve as a dependency to the react-stockcharts when I create it.

If you take a look at our charts, that's exactly what we've done.  The example you provided is almost an exact mirror of how we do our charts, with `Axix` and `DataSeries` subcomponents.  And yes, these are the exact components I'd like to put in react-chart-components, so we both can use them.
