### ISSUE TITLE
Custom x and y accessors

### ISSUE THREAD

**Issue by esbullington** [esbullington/react-d3#81]
We've been kind of assuming people will use `x` and `y` as the names of their respective data names, which is pretty inflexible.  We should probably let them specify a custom x and y accessor.  So, they could do something like:

`<Chart x_accessor="event_dates" y_accessor="event_values" />`

And then instead of using `point.x` and `point.y`, we'd use `point.[props.x_accessor]` etc.

Does this sound reasonable?

**Comment by yang-wei** [comment]
Yeah this sounds true. Same thing for label and value too ?

**Comment by esbullington** [comment]
Done for x and y accessors.  I'm still thinking about label and value accessors.
