### ISSUE TITLE
Charts with more than two dimensions

### ISSUE THREAD

**Issue by frederickfogerty** [esbullington/react-d3#85]
Hey,

I'm looking at creating a new chart (very similar to a candlestick graph) which happens to have four dimensions - something many utils currently do not support.  This will be a common occurrence, as graphs will map a dimension to many things e.g. colour, size

My solution in my personal work was to express data as an array, not an object. This allows any number of dimensions to be used by any graph. This solves #81 as well. 

If we agree on a way to do this I don't mind upgrading the tooling (`utils.flattenData`, `utils.calculateScales`, etc.)

Loving the approach taken by this project currently.

**Comment by esbullington** [comment]
Hi, thanks for your input, and for the compliment -- greatly appreciated.

Regarding new data formats, I'm already in the process of moving everything over to a format that looks like this:
```
[
  { name: 'Exciting data series 1', values: [{"x":0, "y":3}, {"x":1, "y":5}] },
  { name: 'Exciting data series 2', values: [{"x":2, "y":5}, {"x":11, "y":5}] }
]
```
The reason I'm moving to this format is twofold:
1.  It will allow us to leverage a lot of d3's utilities that are based on dataseries having an index.
2.  It's the same data format used by the [Vega visualization grammar](https://github.com/trifacta/vega/wiki/Data).  I would like to eventually be able to support this dataviz specification.  At the least, people could use the same data format for both our project and one using the Vega visualization spec.

That said, note I ultimately want to be in the position where the `values
You do bring up an excellent point about binding data to chart properties, like d3 makes possible.  And while we can't possibly hope to match all of d3's flexibility at the level of abstraction we're working at here, I would *eventually* like look at the possibility at letting users map the properties they pass in to data.  But this will only be possible at the lower level API, that has been discussed in #24 and elsewhere.  So eventually something like (we compile es6 to standard modern browser es5 ):
```
<LineChart width={400} height={200} >
  <DataSeries data={data} label={label} fill={ (d) => d.someValue % 2 === 0 ? "red" : "black" } />
  <DataSeries data={data} label={label} fill={ (d) => d.someOtherValue > 20 ? "blue" : "black" } />
</LineChart>
```
The only difference between using array of objects and multidimensional array with 2d charts is how you access a property in this scenario, using `d.someValue` versus `d[1]`.

Anyway, if I misunderstood what you were proposing, please feel free to correct me.

**Comment by esbullington** [comment]
Argh, hit return too early.  I'm still editing the comment above.

**Comment by frederickfogerty** [comment]
Thanks for the thorough response, much appreciated. I do like the data series approach - I might implement this in my internal work and then submit it as a PR so you can merge it when this becomes the standard.

I'm in the process of upgrading the tooling (`flattenData`) to work better with multidimensional data, and will submit a PR when I'm done, so we can see if we are on the same track.

Regarding #81, you are completely correct.

**Comment by esbullington** [comment]
Thanks again @frederickfogerty merged with 0.2.0 release.  Please feel free to open a new issue if you have any more ideas / concerns, etc.

**Comment by esbullington** [comment]
Hey @frederickfogerty I had to remove your `flattenData` function from utils/index.js since it couldn't handle array accessors.  One of the main reasons I moved to accessors for x and y values was to be able to accomodate nested array data.

If you can add support for array accessors, I'd be happy to add it back.  When added, we also need to document it since otherwise people won't know that the additional aggregated properties are available as properties in the object returned by `flattenData`.

**Comment by frederickfogerty** [comment]
Hey, I was looking at this, and was wondering how mine didn't allow array accessors? If accessors are defined, my code executes `accessors[dimension](item)`, and the existing code executes `xAccessor(item)`. Since `accessors.x = xAccessor` this shouldn't produce different results.

It could've been to do with the following code:

    var accessors = (typeof xAccessor === "object" ? xAccessor : {});
    if (xAccessor && typeof xAccessor === "function") {accessors.x = xAccessor;} 
    if (yAccessor && typeof yAccessor === "function") {accessors.y = yAccessor;}

**Comment by esbullington** [comment]
It's because it's the `xAccessor` you need is defined as `accessors.x` but it's being accessed as `accessors["0"]` in the following ternary expression:

```
+          accesors[dimension] ?
+            accesors[dimension](item[dimension]) :
+            item[dimension]
```

Because `Object.keys` iterates through the nested array by number index (coerced to string), and not by the object properties you need.

**Comment by frederickfogerty** [comment]
Ahhhhh, I see the issue. I'll try get this working tonight, I'm all for making everything generic.
