### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by esbullington** [esbullington/react-d3#96]
Error checking is an issue in some of the charts.  Need to make sure we properly handle empty arrays, missing values, wrong types, etc.  Also need to add more tests to test this error handling.

**Comment by yang-wei** [comment]
Although not related to this, I noticed that in our prop validation, we do declare the type of data (such as `array`, `func`) but we can make it more clear by adding `isRequired`. 

[Reference](http://facebook.github.io/react/docs/reusable-components.html#prop-validation)

Can't really follow all the updates now(busy month) but will surely check it our when I have time. Congrats on the release.

**Comment by esbullington** [comment]
Hey, glad to hear from you, @yang-wei  Understood about your busy month -- we'll look forward to seeing you more in March, if things slow down for you then.

And I agree that we could be taking better advantage of the `isRequired`.  I'll try to remember to add that to all the charts.

Thanks again for all your help with the 0.2 release!

**Comment by yang-wei** [comment]
@esbullington Oops I deleted my comment because I saw you actually did that in some places like `axes.jsx`. Yes I will be back soon =)

**Comment by yang-wei** [comment]
close due to inactive
